<?php

declare(strict_types=1);

namespace Divi5Validator;

/**
 * GENERATED by scripts/promote-modules.php from docs/module-verification-*.json.
 * Do not edit by hand: every entry is backed by a render-verification record.
 */
final class VerifiedModules
{
    public const DIVI_VERSION = '5.14.0';

    public const LEAF = [];

    public const STRUCTURAL = [];

    public const COLUMN_CHILDREN = [];

    public const SECTION_CHILDREN = [];

    public const CHILDREN = [];
}
