<?php
/**
 * generate-image-pack.php — builds the plugin's built-in image pack.
 *
 * Original artwork generated by scripts/generate-image-pack.php, © JHMG, released under GPL-2.0-or-later.
 *
 * Usage: php scripts/generate-image-pack.php [outDir]   (default: wp-plugin/assets/images)
 *
 * Writes every SVG, manifest.json and README.txt into outDir. Dev-only: this
 * script is not shipped in the plugin zip. It is fully deterministic — every
 * "random" variation comes from a fixed integer seed per image fed into a small
 * integer LCG, and every computed coordinate is rounded to one decimal and
 * formatted identically — so a fresh run reproduces the committed files byte
 * for byte (tests/ImagePackTest.php checks this). Standard library only.
 */

declare(strict_types=1);

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

/** Deterministic 31-bit LCG (identical on every 64-bit PHP build). */
final class Rng
{
    private int $s;

    public function __construct(int $seed)
    {
        $this->s = ($seed & 0x7fffffff) ?: 1;
    }

    public function next(): float
    {
        $this->s = ($this->s * 1103515245 + 12345) & 0x7fffffff;

        return ($this->s >> 4) / 134217728; // drop the weak low bits
    }

    public function range(float $a, float $b): float
    {
        return $a + ($b - $a) * $this->next();
    }

    public function int(int $a, int $b): int
    {
        return min($b, $a + (int) floor($this->next() * ($b - $a + 1)));
    }
}

/** Format a number: one decimal, no trailing ".0", never "-0". */
function f(float|int $v): string
{
    $r = round((float) $v, 1);
    $s = number_format($r, 1, '.', '');
    if (str_ends_with($s, '.0')) {
        $s = substr($s, 0, -2);
    }

    return $s === '-0' ? '0' : $s;
}

/** Build an element. Floats are formatted with f(); strings are XML-escaped. */
function el(string $name, array $a = [], ?string $inner = null): string
{
    $s = '<' . $name;
    foreach ($a as $k => $v) {
        if ($v === null) {
            continue;
        }
        $s .= ' ' . $k . '="' . (is_float($v) ? f($v) : htmlspecialchars((string) $v, ENT_XML1 | ENT_QUOTES, 'UTF-8')) . '"';
    }

    return $inner === null ? $s . '/>' : $s . '>' . $inner . '</' . $name . '>';
}

/** @param list<array{0:float|int,1:string,2?:float|int}> $stops */
function stops(array $stops): string
{
    $o = '';
    foreach ($stops as $st) {
        $o .= el('stop', ['offset' => (float) $st[0], 'stop-color' => $st[1], 'stop-opacity' => isset($st[2]) ? (float) $st[2] : null]);
    }

    return $o;
}

function lin(string $id, array $stops, float $x1 = 0, float $y1 = 0, float $x2 = 0, float $y2 = 1, array $extra = []): string
{
    return el('linearGradient', ['id' => $id, 'x1' => $x1, 'y1' => $y1, 'x2' => $x2, 'y2' => $y2] + $extra, stops($stops));
}

function rad(string $id, array $stops, array $extra = []): string
{
    return el('radialGradient', ['id' => $id] + $extra, stops($stops));
}

/** A soft glow: radial gradient from colour at opacity $op to transparent. */
function glowDef(string $id, string $color, float $op): string
{
    return rad($id, [[0, $color, $op], [0.55, $color, $op * 0.45], [1, $color, 0]]);
}

function blurDef(string $id, float $std): string
{
    return el('filter', ['id' => $id, 'x' => '-50%', 'y' => '-50%', 'width' => '200%', 'height' => '200%'], el('feGaussianBlur', ['stdDeviation' => $std]));
}

function shadowDef(string $id, string $color, float $op, float $dy = 18, float $std = 22): string
{
    // userSpaceOnUse region = the whole canvas, so blurred shadows of small shapes are never clipped into boxes.
    return el('filter', ['id' => $id, 'filterUnits' => 'userSpaceOnUse', 'x' => '-10%', 'y' => '-10%', 'width' => '120%', 'height' => '130%'],
        el('feDropShadow', ['dx' => 0, 'dy' => $dy, 'stdDeviation' => $std, 'flood-color' => $color, 'flood-opacity' => $op]));
}

/**
 * Smooth path through points (Catmull-Rom converted to cubic Béziers).
 * @param list<array{0:float,1:float}> $p
 */
function smooth(array $p, bool $closed = false): string
{
    $n = count($p);
    $get = static function (int $i) use ($p, $n, $closed): array {
        if ($closed) {
            return $p[(($i % $n) + $n) % $n];
        }

        return $p[max(0, min($n - 1, $i))];
    };
    $d    = 'M' . f($p[0][0]) . ' ' . f($p[0][1]);
    $last = $closed ? $n : $n - 1;
    for ($i = 0; $i < $last; $i++) {
        $p0 = $get($i - 1);
        $p1 = $get($i);
        $p2 = $get($i + 1);
        $p3 = $get($i + 2);
        $c1 = [$p1[0] + ($p2[0] - $p0[0]) / 6, $p1[1] + ($p2[1] - $p0[1]) / 6];
        $c2 = [$p2[0] - ($p3[0] - $p1[0]) / 6, $p2[1] - ($p3[1] - $p1[1]) / 6];
        $d .= 'C' . f($c1[0]) . ' ' . f($c1[1]) . ' ' . f($c2[0]) . ' ' . f($c2[1]) . ' ' . f($p2[0]) . ' ' . f($p2[1]);
    }

    return $closed ? $d . 'Z' : $d;
}

/** Points of a horizontal wave across [x0,x1]. */
function wavePoints(float $x0, float $x1, float $y, float $amp, float $len, float $phase, int $steps = 12, float $amp2 = 0, float $len2 = 1): array
{
    $pts = [];
    for ($i = 0; $i <= $steps; $i++) {
        $x     = $x0 + ($x1 - $x0) * $i / $steps;
        $pts[] = [$x, $y + $amp * sin($x / $len * 2 * M_PI + $phase) + $amp2 * sin($x / $len2 * 2 * M_PI + $phase * 1.7)];
    }

    return $pts;
}

/** Filled wave area from a wave line down to $bottom. */
function waveArea(array $pts, float $bottom): string
{
    $first = $pts[0];
    $last  = $pts[count($pts) - 1];

    return smooth($pts) . 'L' . f($last[0]) . ' ' . f($bottom) . 'L' . f($first[0]) . ' ' . f($bottom) . 'Z';
}

/** Organic closed blob. */
function blob(Rng $r, float $cx, float $cy, float $rad, int $n = 7, float $wobble = 0.22, float $sy = 1.0): string
{
    $pts = [];
    for ($i = 0; $i < $n; $i++) {
        $a     = 2 * M_PI * $i / $n;
        $rr    = $rad * (1 + $r->range(-$wobble, $wobble));
        $pts[] = [$cx + $rr * cos($a), $cy + $rr * sin($a) * $sy];
    }

    return smooth($pts, true);
}

/** Four-point sparkle centred on (x,y). */
function sparkle(float $x, float $y, float $s, string $fill, float $op = 1.0): string
{
    $k = $s * 0.22;
    $d = 'M' . f($x) . ' ' . f($y - $s) . 'Q' . f($x + $k) . ' ' . f($y - $k) . ' ' . f($x + $s) . ' ' . f($y)
        . 'Q' . f($x + $k) . ' ' . f($y + $k) . ' ' . f($x) . ' ' . f($y + $s)
        . 'Q' . f($x - $k) . ' ' . f($y + $k) . ' ' . f($x - $s) . ' ' . f($y)
        . 'Q' . f($x - $k) . ' ' . f($y - $k) . ' ' . f($x) . ' ' . f($y - $s) . 'Z';

    return el('path', ['d' => $d, 'fill' => $fill, 'opacity' => $op < 1 ? $op : null]);
}

function plus(float $x, float $y, float $s, string $stroke, float $w = 6, float $op = 1.0): string
{
    return el('path', ['d' => 'M' . f($x - $s) . ' ' . f($y) . 'H' . f($x + $s) . 'M' . f($x) . ' ' . f($y - $s) . 'V' . f($y + $s),
        'stroke' => $stroke, 'stroke-width' => $w, 'stroke-linecap' => 'round', 'opacity' => $op < 1 ? $op : null]);
}

function rr(float $x, float $y, float $w, float $h, float $r, string $fill, array $extra = []): string
{
    return el('rect', ['x' => $x, 'y' => $y, 'width' => $w, 'height' => $h, 'rx' => $r, 'fill' => $fill] + $extra);
}

function circ(float $cx, float $cy, float $r, string $fill, array $extra = []): string
{
    return el('circle', ['cx' => $cx, 'cy' => $cy, 'r' => $r, 'fill' => $fill] + $extra);
}

/** Dot grid as individual circles inside a box (used for small decorative grids). */
function dotGrid(float $x, float $y, int $cols, int $rows, float $gap, float $r, string $fill, float $op): string
{
    $o = '';
    for ($j = 0; $j < $rows; $j++) {
        for ($i = 0; $i < $cols; $i++) {
            $o .= circ($x + $i * $gap, $y + $j * $gap, $r, $fill);
        }
    }

    return el('g', ['opacity' => $op], $o);
}

function svg(int $w, int $h, string $title, string $defs, string $body): string
{
    return '<svg xmlns="http://www.w3.org/2000/svg" width="' . $w . '" height="' . $h . '" viewBox="0 0 ' . $w . ' ' . $h . '" role="img">' . "\n"
        . el('title', [], htmlspecialchars($title, ENT_XML1, 'UTF-8')) . "\n"
        . ($defs !== '' ? '<defs>' . $defs . '</defs>' . "\n" : '')
        . $body . "\n"
        . '</svg>' . "\n";
}

// ---------------------------------------------------------------------------
// Palettes (Tailwind-like ramps; 50 = lightest, 950 = darkest; acc = accent)
// ---------------------------------------------------------------------------

const PAL = [
    'blue'   => ['950' => '#0a1838', '900' => '#102a63', '800' => '#1e3a8a', '700' => '#1d4ed8', '600' => '#2563eb', '500' => '#3b82f6', '400' => '#60a5fa', '300' => '#93c5fd', '200' => '#bfdbfe', '100' => '#dbeafe', '50' => '#eff6ff', 'acc' => '#22d3ee', 'acc2' => '#f59e0b'],
    'purple' => ['950' => '#1a0633', '900' => '#2e1065', '800' => '#4c1d95', '700' => '#6d28d9', '600' => '#7c3aed', '500' => '#8b5cf6', '400' => '#a78bfa', '300' => '#c4b5fd', '200' => '#ddd6fe', '100' => '#ede9fe', '50' => '#f5f3ff', 'acc' => '#f472b6', 'acc2' => '#22d3ee'],
    'teal'   => ['950' => '#03211f', '900' => '#134e4a', '800' => '#115e59', '700' => '#0f766e', '600' => '#0d9488', '500' => '#14b8a6', '400' => '#2dd4bf', '300' => '#5eead4', '200' => '#99f6e4', '100' => '#ccfbf1', '50' => '#f0fdfa', 'acc' => '#a3e635', 'acc2' => '#fbbf24'],
    'sunset' => ['950' => '#2a0a1a', '900' => '#4a1230', '800' => '#7c2d12', '700' => '#c2410c', '600' => '#ea580c', '500' => '#f97316', '400' => '#fb923c', '300' => '#fdba74', '200' => '#fed7aa', '100' => '#ffedd5', '50' => '#fff7ed', 'acc' => '#f43f5e', 'acc2' => '#fbbf24'],
    'forest' => ['950' => '#03190d', '900' => '#052e16', '800' => '#14532d', '700' => '#15803d', '600' => '#16a34a', '500' => '#22c55e', '400' => '#4ade80', '300' => '#86efac', '200' => '#bbf7d0', '100' => '#dcfce7', '50' => '#f0fdf4', 'acc' => '#facc15', 'acc2' => '#a16207'],
    'slate'  => ['950' => '#020617', '900' => '#0f172a', '800' => '#1e293b', '700' => '#334155', '600' => '#475569', '500' => '#64748b', '400' => '#94a3b8', '300' => '#cbd5e1', '200' => '#e2e8f0', '100' => '#f1f5f9', '50' => '#f8fafc', 'acc' => '#38bdf8', 'acc2' => '#f43f5e'],
    'rose'   => ['950' => '#2d0510', '900' => '#4c0519', '800' => '#881337', '700' => '#be123c', '600' => '#e11d48', '500' => '#f43f5e', '400' => '#fb7185', '300' => '#fda4af', '200' => '#fecdd3', '100' => '#ffe4e6', '50' => '#fff1f2', 'acc' => '#c026d3', 'acc2' => '#fbbf24'],
    'gold'   => ['950' => '#1a1005', '900' => '#3b2307', '800' => '#78350f', '700' => '#b45309', '600' => '#d97706', '500' => '#f59e0b', '400' => '#fbbf24', '300' => '#fcd34d', '200' => '#fde68a', '100' => '#fef3c7', '50' => '#fffbeb', 'acc' => '#fef08a', 'acc2' => '#0f766e'],
];

// ---------------------------------------------------------------------------
// HERO (1600×900) — dark, rich backgrounds; white text stays readable.
// ---------------------------------------------------------------------------

function heroBase(array $c, string $from, string $to, string $mid = ''): string
{
    $st = $mid === '' ? [[0, $from], [1, $to]] : [[0, $from], [0.55, $mid], [1, $to]];

    return lin('bg', $st, 0, 0, 1, 1);
}

/** Darkening scrim on the left/centre so overlaid white text keeps contrast. */
function scrimDef(string $color, float $op): string
{
    return rad('scrim', [[0, $color, $op], [1, $color, 0]], ['cx' => '.38', 'cy' => '.45', 'r' => '.6']);
}

function hero_blue(Rng $r): array
{
    $c    = PAL['blue'];
    $defs = heroBase($c, $c['950'], $c['700'], $c['900'])
        . glowDef('g1', $c['500'], 0.7) . glowDef('g2', $c['acc'], 0.45) . glowDef('g3', '#6366f1', 0.6)
        . lin('w1', [[0, $c['400'], 0.0], [0.5, $c['300'], 0.35], [1, $c['acc'], 0.15]], 0, 0, 1, 0)
        . lin('w2', [[0, $c['600'], 0.5], [1, $c['acc'], 0.35]], 0, 0, 1, 0)
        . lin('w3', [[0, $c['800'], 0.9], [1, $c['600'], 0.8]], 0, 0, 1, 0)
        . scrimDef($c['950'], 0.45);
    $b = rr(0, 0, 1600, 900, 0, 'url(#bg)')
        . circ(1350, 120, 720, 'url(#g1)') . circ(150, 820, 620, 'url(#g3)') . circ(1150, 820, 520, 'url(#g2)');
    // Flowing hairlines.
    $lines = '';
    for ($k = 0; $k < 18; $k++) {
        $pts    = wavePoints(-40, 1640, 520 + $k * 9, 70 + $k * 2, 1500, 0.6 + $k * 0.06, 14, 20, 640);
        $lines .= el('path', ['d' => smooth($pts)]);
    }
    $b .= el('g', ['fill' => 'none', 'stroke' => '#ffffff', 'stroke-opacity' => '.10', 'stroke-width' => 1.5], $lines);
    $b .= el('path', ['d' => waveArea(wavePoints(-40, 1640, 690, 50, 1300, 2.1, 12), 900), 'fill' => 'url(#w1)']);
    $b .= el('path', ['d' => waveArea(wavePoints(-40, 1640, 750, 44, 1100, 3.4, 12), 900), 'fill' => 'url(#w2)']);
    $b .= el('path', ['d' => waveArea(wavePoints(-40, 1640, 812, 30, 900, 0.8, 12), 900), 'fill' => 'url(#w3)']);
    $b .= rr(0, 0, 1600, 900, 0, 'url(#scrim)');
    $b .= dotGrid(1240, 120, 8, 5, 26, 2.2, '#ffffff', 0.18);
    $b .= sparkle(1180, 300, 14, '#ffffff', 0.7) . sparkle(260, 170, 9, '#ffffff', 0.5);

    return [$defs, $b];
}

function hero_purple(Rng $r): array
{
    $c    = PAL['purple'];
    $defs = heroBase($c, $c['950'], $c['800'], $c['900'])
        . glowDef('g1', $c['600'], 0.75) . glowDef('g2', $c['acc'], 0.45) . glowDef('g3', $c['acc2'], 0.3)
        . lin('rb', [[0, $c['acc'], 0], [0.35, $c['acc'], 0.55], [0.7, $c['400'], 0.5], [1, $c['acc2'], 0]], 0, 0, 1600, 0, ['gradientUnits' => 'userSpaceOnUse'])
        . blurDef('bl', 40) . scrimDef($c['950'], 0.4);
    $b = rr(0, 0, 1600, 900, 0, 'url(#bg)')
        . circ(1250, 300, 700, 'url(#g1)') . circ(300, 900, 500, 'url(#g2)') . circ(1500, 850, 400, 'url(#g3)');
    // Aurora: a blurred band plus a ribbon of fine lines.
    $band = wavePoints(-100, 1700, 470, 140, 1700, 4.0, 10, 30, 700);
    $b .= el('path', ['d' => smooth($band), 'fill' => 'none', 'stroke' => 'url(#rb)', 'stroke-width' => 120, 'filter' => 'url(#bl)', 'opacity' => '.8']);
    $lines = '';
    for ($k = 0; $k < 26; $k++) {
        $pts    = wavePoints(-60, 1660, 400 + $k * 6, 140 - $k * 1.5, 1700, 4.0 + $k * 0.035, 16, 30, 700);
        $lines .= el('path', ['d' => smooth($pts)]);
    }
    $b .= el('g', ['fill' => 'none', 'stroke' => 'url(#rb)', 'stroke-width' => 1.4], $lines);
    $b .= rr(0, 0, 1600, 900, 0, 'url(#scrim)');
    for ($i = 0; $i < 40; $i++) {
        $b .= circ($r->range(0, 1600), $r->range(0, 900), $r->range(0.8, 2.2), '#ffffff', ['opacity' => $r->range(0.2, 0.7)]);
    }
    $b .= sparkle(1320, 170, 16, '#ffffff', 0.8) . sparkle(980, 120, 8, '#ffffff', 0.6);

    return [$defs, $b];
}

function hero_teal(Rng $r): array
{
    $c    = PAL['teal'];
    $defs = heroBase($c, $c['950'], $c['800'], $c['900'])
        . glowDef('g1', $c['400'], 0.55) . glowDef('g2', $c['300'], 0.22) . glowDef('g3', $c['600'], 0.6)
        . scrimDef($c['950'], 0.45);
    $b = rr(0, 0, 1600, 900, 0, 'url(#bg)')
        . circ(1260, 460, 620, 'url(#g3)') . circ(1260, 460, 260, 'url(#g1)') . circ(200, 120, 420, 'url(#g2)');
    $rings = '';
    for ($k = 1; $k <= 18; $k++) {
        $rings .= el('circle', ['cx' => 1260, 'cy' => 460, 'r' => (float) (60 + $k * 48), 'stroke-opacity' => (float) max(0.03, 0.24 - $k * 0.012)]);
    }
    $b .= el('g', ['fill' => 'none', 'stroke' => '#ffffff', 'stroke-width' => 1.5], $rings);
    // Orbiting dots on a few rings.
    foreach ([[3, 0.6], [6, 2.4], [9, 4.1], [12, 5.3]] as [$k, $a]) {
        $rad = 60 + $k * 48;
        $b  .= circ(1260 + $rad * cos($a), 460 + $rad * sin($a), 7, $k % 2 ? $c['300'] : $c['acc']);
    }
    $b .= circ(1260, 460, 46, $c['300'], ['opacity' => '.9']) . circ(1260, 460, 22, '#ffffff', ['opacity' => '.85']);
    $b .= el('path', ['d' => waveArea(wavePoints(-40, 1640, 800, 26, 900, 1.3, 10), 900), 'fill' => $c['950'], 'opacity' => '.55']);
    $b .= rr(0, 0, 1600, 900, 0, 'url(#scrim)');
    $b .= dotGrid(90, 640, 10, 6, 24, 2, $c['200'], 0.16);

    return [$defs, $b];
}

function hero_sunset(Rng $r): array
{
    $c    = PAL['sunset'];
    $defs = lin('bg', [[0, '#1e0b2e'], [0.45, $c['900']], [0.78, '#a3330f'], [1, $c['600']]])
        . lin('sun', [[0, '#fde68a'], [0.6, $c['400']], [1, $c['acc']]])
        . glowDef('g1', $c['500'], 0.65) . glowDef('g2', $c['acc'], 0.35)
        . lin('d1', [[0, '#7a1f2b'], [1, '#4a1230']]) . lin('d2', [[0, '#561634'], [1, '#2f0c25']]) . lin('d3', [[0, '#2f0c25'], [1, '#1a0716']])
        . el('clipPath', ['id' => 'sc'], circ(1260, 610, 180, '#000'));
    $b = rr(0, 0, 1600, 900, 0, 'url(#bg)')
        . circ(1260, 610, 600, 'url(#g1)') . circ(260, 260, 420, 'url(#g2)');
    $b .= circ(1260, 610, 180, 'url(#sun)');
    // Retro horizontal cuts through the sun.
    $cuts = '';
    for ($k = 0; $k < 6; $k++) {
        $y     = 520 + $k * 24;
        $cuts .= rr(1060, $y, 420, 3 + $k * 2.4, 0, '#4a1230');
    }
    $b .= el('g', ['clip-path' => 'url(#sc)', 'opacity' => '.85'], $cuts);
    $b .= el('path', ['d' => waveArea(wavePoints(-40, 1640, 660, 40, 1500, 0.4, 10, 14, 520), 900), 'fill' => 'url(#d1)', 'opacity' => '.95']);
    $b .= el('path', ['d' => waveArea(wavePoints(-40, 1640, 740, 46, 1200, 2.6, 10, 10, 430), 900), 'fill' => 'url(#d2)']);
    $b .= el('path', ['d' => waveArea(wavePoints(-40, 1640, 820, 28, 1000, 4.4, 10), 900), 'fill' => 'url(#d3)']);
    for ($i = 0; $i < 46; $i++) {
        $b .= circ($r->range(0, 1600), $r->range(0, 420), $r->range(0.8, 2.0), '#ffe4d1', ['opacity' => $r->range(0.25, 0.75)]);
    }

    return [$defs, $b];
}

/** Jagged mountain ridge by midpoint displacement. */
function ridge(Rng $r, float $y, float $rough, int $levels, float $bottom): string
{
    $pts = [[-20.0, $y + $r->range(-$rough, $rough)], [1620.0, $y + $r->range(-$rough, $rough)]];
    $amp = $rough;
    for ($l = 0; $l < $levels; $l++) {
        $next = [];
        for ($i = 0; $i < count($pts) - 1; $i++) {
            $next[] = $pts[$i];
            $next[] = [($pts[$i][0] + $pts[$i + 1][0]) / 2, ($pts[$i][1] + $pts[$i + 1][1]) / 2 + $r->range(-$amp, $amp)];
        }
        $next[] = $pts[count($pts) - 1];
        $pts    = $next;
        $amp   *= 0.55;
    }
    $d = 'M' . f($pts[0][0]) . ' ' . f($pts[0][1]);
    foreach (array_slice($pts, 1) as $p) {
        $d .= 'L' . f($p[0]) . ' ' . f($p[1]);
    }

    return $d . 'L1620 ' . f($bottom) . 'L-20 ' . f($bottom) . 'Z';
}

function hero_forest(Rng $r): array
{
    $c    = PAL['forest'];
    $defs = lin('bg', [[0, '#04140c'], [0.55, '#0b3a22'], [1, '#2f6b45']])
        . glowDef('g1', '#ecfccb', 0.3) . glowDef('g2', $c['500'], 0.3)
        . lin('mist', [[0, '#d1fae5', 0], [0.6, '#d1fae5', 0.13], [1, '#d1fae5', 0]]);
    $b = rr(0, 0, 1600, 900, 0, 'url(#bg)') . circ(1230, 230, 380, 'url(#g1)') . circ(300, 600, 520, 'url(#g2)');
    $b .= circ(1230, 230, 62, '#ecfccb', ['opacity' => '.92']);
    for ($i = 0; $i < 60; $i++) {
        $b .= circ($r->range(0, 1600), $r->range(0, 380), $r->range(0.7, 1.9), '#f0fdf4', ['opacity' => $r->range(0.2, 0.7)]);
    }
    $layers = [[470, 110, '#2d5f43'], [560, 90, '#1f4a33'], [640, 80, '#153a27'], [720, 60, '#0d2b1c'], [800, 40, '#071a10']];
    foreach ($layers as $i => [$y, $rough, $col]) {
        $b .= el('path', ['d' => ridge($r, $y, $rough, 7, 900), 'fill' => $col]);
        if ($i < 4) {
            $b .= rr(0, $y - 30, 1600, 150, 0, 'url(#mist)');
        }
    }

    return [$defs, $b];
}

function hero_slate(Rng $r): array
{
    $c    = PAL['slate'];
    $defs = heroBase($c, $c['950'], $c['800'], $c['900'])
        . glowDef('g1', $c['acc'], 0.45) . glowDef('g2', '#6366f1', 0.35)
        . lin('fade', [[0, '#ffffff', 0], [1, '#ffffff', 1]])
        . el('mask', ['id' => 'fm'], rr(0, 560, 1600, 340, 0, 'url(#fade)'))
        . lin('glass', [[0, '#ffffff', 0.14], [1, '#ffffff', 0.04]], 0, 0, 1, 1)
        . scrimDef($c['950'], 0.35);
    $b = rr(0, 0, 1600, 900, 0, 'url(#bg)') . circ(1180, 420, 560, 'url(#g1)') . circ(220, 160, 480, 'url(#g2)');
    // Perspective grid floor.
    $g  = '';
    $vx = 800;
    $vy = 520;
    for ($k = -16; $k <= 16; $k++) {
        $g .= 'M' . f($vx + $k * 12) . ' ' . f($vy + 40) . 'L' . f($vx + $k * 160) . ' 900';
    }
    foreach ([580, 600, 628, 664, 712, 774, 852] as $y) {
        $g .= 'M0 ' . $y . 'H1600';
    }
    $b .= el('path', ['d' => $g, 'stroke' => $c['acc'], 'stroke-opacity' => '.35', 'stroke-width' => 1.2, 'fill' => 'none', 'mask' => 'url(#fm)']);
    // Floating glass panels with UI hints.
    $panel = static function (float $x, float $y, float $w, float $h, string $acc) : string {
        return rr($x, $y, $w, $h, 18, 'url(#glass)', ['stroke' => '#ffffff', 'stroke-opacity' => '.18'])
            . rr($x + 24, $y + 24, $w * 0.45, 12, 6, '#ffffff', ['opacity' => '.45'])
            . rr($x + 24, $y + 46, $w * 0.3, 10, 5, '#ffffff', ['opacity' => '.22'])
            . rr($x + 24, $y + $h - 40, $w - 48, 14, 7, '#ffffff', ['opacity' => '.10'])
            . rr($x + 24, $y + $h - 40, ($w - 48) * 0.62, 14, 7, $acc, ['opacity' => '.85']);
    };
    $b .= $panel(1040, 200, 330, 170, $c['acc']) . $panel(1180, 420, 280, 150, '#818cf8') . $panel(960, 500, 200, 120, '#34d399');
    $b .= circ(1370, 200, 26, $c['acc'], ['opacity' => '.9']) . circ(1370, 200, 10, '#ffffff');
    $b .= rr(0, 0, 1600, 900, 0, 'url(#scrim)');
    $b .= dotGrid(100, 110, 6, 4, 24, 2, '#ffffff', 0.15);

    return [$defs, $b];
}

function hero_rose(Rng $r): array
{
    $c    = PAL['rose'];
    $defs = heroBase($c, $c['950'], $c['800'], $c['900'])
        . blurDef('bl', 70) . scrimDef($c['950'], 0.4);
    $b = rr(0, 0, 1600, 900, 0, 'url(#bg)');
    $blobs = '';
    foreach ([[1250, 260, 280, $c['500'], .55], [1000, 640, 300, $c['acc'], .4], [1450, 700, 220, $c['acc2'], .3], [300, 780, 260, $c['500'], .45], [520, 80, 200, $c['acc'], .35]] as [$x, $y, $rad, $col, $op]) {
        $blobs .= el('path', ['d' => blob($r, $x, $y, $rad, 7, 0.25), 'fill' => $col, 'opacity' => $op]);
    }
    $b .= el('g', ['filter' => 'url(#bl)'], $blobs);
    // Crisp outline accents.
    $b .= el('path', ['d' => blob($r, 1200, 450, 300, 8, 0.12), 'fill' => 'none', 'stroke' => '#ffffff', 'stroke-opacity' => '.18', 'stroke-width' => 2]);
    $b .= el('path', ['d' => blob($r, 1200, 450, 240, 8, 0.12), 'fill' => 'none', 'stroke' => '#ffffff', 'stroke-opacity' => '.10', 'stroke-width' => 2]);
    $b .= circ(1420, 210, 40, '#ffffff', ['opacity' => '.12']) . circ(980, 760, 18, '#ffffff', ['opacity' => '.2']);
    $b .= rr(0, 0, 1600, 900, 0, 'url(#scrim)');
    $b .= sparkle(1100, 180, 14, '#ffffff', 0.7) . sparkle(1480, 520, 10, '#ffffff', 0.5);

    return [$defs, $b];
}

function hero_gold(Rng $r): array
{
    $c    = PAL['gold'];
    $defs = lin('bg', [[0, '#120a03'], [0.5, '#2e1a06'], [1, '#5a300b']], 0, 0, 1, 1)
        . glowDef('g1', $c['500'], 0.5) . glowDef('g2', $c['300'], 0.3)
        . lin('beam', [[0, $c['200'], 0.22], [1, $c['200'], 0]], 1, 0, 0, 1)
        . blurDef('bl', 6) . blurDef('bl2', 26);
    $b = rr(0, 0, 1600, 900, 0, 'url(#bg)') . circ(1300, 300, 700, 'url(#g1)') . circ(1500, 80, 300, 'url(#g2)');
    $b .= el('path', ['d' => 'M1600 0L1600 260L520 900L180 900Z', 'fill' => 'url(#beam)', 'filter' => 'url(#bl2)']);
    $soft = '';
    $sharp = '';
    for ($i = 0; $i < 34; $i++) {
        $x   = $r->range(700, 1600);
        $y   = $r->range(0, 900);
        $rad = $r->range(8, 70);
        $col = [$c['400'], $c['300'], $c['200'], '#fff7d6'][$i % 4];
        $op  = $r->range(0.08, 0.32);
        if ($i % 3 === 0) {
            $sharp .= circ($x, $y, $rad, $col, ['opacity' => $op, 'stroke' => $c['200'], 'stroke-opacity' => '.25', 'stroke-width' => 1.5]);
        } else {
            $soft .= circ($x, $y, $rad, $col, ['opacity' => $op]);
        }
    }
    $b .= el('g', ['filter' => 'url(#bl)'], $soft) . $sharp;
    // Fine gold arcs.
    $b .= el('path', ['d' => 'M760 900C900 560 1180 380 1600 330', 'stroke' => $c['300'], 'stroke-opacity' => '.45', 'stroke-width' => 1.6, 'fill' => 'none']);
    $b .= el('path', ['d' => 'M840 900C980 600 1240 440 1600 400', 'stroke' => $c['300'], 'stroke-opacity' => '.25', 'stroke-width' => 1.2, 'fill' => 'none']);
    $b .= sparkle(1240, 180, 18, '#fff7d6', 0.85) . sparkle(1460, 460, 10, '#fff7d6', 0.6);

    return [$defs, $b];
}

// ---------------------------------------------------------------------------
// SECTION BACKGROUNDS (1600×900) — quiet patterns, low contrast.
// ---------------------------------------------------------------------------

function vignetteMask(string $id, bool $centerVisible): string
{
    $a = $centerVisible ? 1 : 0;

    return rad($id . 'g', [[0, '#ffffff', $a], [1, '#ffffff', 1 - $a]], ['cx' => '.5', 'cy' => '.5', 'r' => '.75'])
        . el('mask', ['id' => $id], rr(0, 0, 1600, 900, 0, 'url(#' . $id . 'g)'));
}

function bg_slate(Rng $r): array
{
    $c    = PAL['slate'];
    $defs = lin('bg', [[0, $c['50']], [1, $c['100']]], 0, 0, 1, 1)
        . el('pattern', ['id' => 'p', 'width' => 28, 'height' => 28, 'patternUnits' => 'userSpaceOnUse'], circ(14, 14, 1.8, $c['400']))
        . vignetteMask('m', false) . glowDef('g1', $c['acc'], 0.12) . glowDef('g2', '#a5b4fc', 0.14);
    $b = rr(0, 0, 1600, 900, 0, 'url(#bg)') . circ(1500, 80, 520, 'url(#g1)') . circ(80, 860, 520, 'url(#g2)')
        . rr(0, 0, 1600, 900, 0, 'url(#p)', ['mask' => 'url(#m)', 'opacity' => '.75']);

    return [$defs, $b];
}

function bg_blue(Rng $r): array
{
    $c    = PAL['blue'];
    $defs = lin('bg', [[0, '#f5f9ff'], [1, $c['50']]])
        . el('pattern', ['id' => 'p', 'width' => 48, 'height' => 48, 'patternUnits' => 'userSpaceOnUse'],
            el('path', ['d' => 'M48 0H0V48', 'fill' => 'none', 'stroke' => $c['300'], 'stroke-width' => 1]))
        . vignetteMask('m', true) . glowDef('g1', $c['300'], 0.35) . glowDef('g2', $c['acc'], 0.18);
    $b = rr(0, 0, 1600, 900, 0, 'url(#bg)') . circ(1350, 150, 500, 'url(#g1)') . circ(250, 800, 420, 'url(#g2)')
        . rr(0, 0, 1600, 900, 0, 'url(#p)', ['mask' => 'url(#m)', 'opacity' => '.5']);

    return [$defs, $b];
}

function bg_purple(Rng $r): array
{
    $c    = PAL['purple'];
    $defs = lin('bg', [[0, $c['950']], [1, $c['900']]], 0, 0, 1, 1)
        . el('pattern', ['id' => 'p', 'width' => 22, 'height' => 22, 'patternUnits' => 'userSpaceOnUse', 'patternTransform' => 'rotate(35)'],
            el('path', ['d' => 'M0 0V22', 'stroke' => '#ffffff', 'stroke-width' => 1.2]))
        . vignetteMask('m', false) . glowDef('g1', $c['600'], 0.45) . glowDef('g2', $c['acc'], 0.18);
    $b = rr(0, 0, 1600, 900, 0, 'url(#bg)') . circ(1450, 100, 620, 'url(#g1)') . circ(100, 900, 480, 'url(#g2)')
        . rr(0, 0, 1600, 900, 0, 'url(#p)', ['mask' => 'url(#m)', 'opacity' => '.13']);

    return [$defs, $b];
}

function bg_teal(Rng $r): array
{
    $c    = PAL['teal'];
    $defs = lin('bg', [[0, $c['50']], [1, '#e6fbf6']]);
    $b    = rr(0, 0, 1600, 900, 0, 'url(#bg)');
    $lines = '';
    for ($k = 0; $k < 22; $k++) {
        $pts    = wavePoints(-40, 1640, 40 + $k * 40, 28 + ($k % 5) * 3, 800, $k * 0.32, 14);
        $lines .= el('path', ['d' => smooth($pts)]);
    }
    $b .= el('g', ['fill' => 'none', 'stroke' => $c['300'], 'stroke-width' => 1.5, 'opacity' => '.45'], $lines);
    $b .= el('path', ['d' => waveArea(wavePoints(-40, 1640, 780, 34, 1100, 1.0, 10), 900), 'fill' => $c['100'], 'opacity' => '.8']);
    $b .= el('path', ['d' => waveArea(wavePoints(-40, 1640, 830, 26, 900, 2.6, 10), 900), 'fill' => $c['200'], 'opacity' => '.5']);

    return [$defs, $b];
}

function bg_rose(Rng $r): array
{
    $c    = PAL['rose'];
    $defs = lin('bg', [[0, $c['50']], [1, '#fff7f8']]) . blurDef('bl', 90);
    $b    = rr(0, 0, 1600, 900, 0, 'url(#bg)');
    $blobs = '';
    foreach ([[1300, 160, 330, $c['200'], .8], [180, 720, 340, '#fbcfe8', .75], [1450, 800, 260, '#fde68a', .55], [700, 60, 220, '#e9d5ff', .55]] as [$x, $y, $rad, $col, $op]) {
        $blobs .= el('path', ['d' => blob($r, $x, $y, $rad, 7, 0.25), 'fill' => $col, 'opacity' => $op]);
    }
    $b .= el('g', ['filter' => 'url(#bl)'], $blobs);

    return [$defs, $b];
}

function bg_forest(Rng $r): array
{
    $c    = PAL['forest'];
    $defs = lin('bg', [[0, $c['950']], [1, $c['900']]], 0, 0, 1, 1) . glowDef('g1', $c['600'], 0.3);
    $b    = rr(0, 0, 1600, 900, 0, 'url(#bg)') . circ(1300, 650, 600, 'url(#g1)');
    $topo = '';
    foreach ([[1250, 620, 15], [260, 180, 11], [820, 900, 8]] as $ci => [$cx, $cy, $n]) {
        $rr2  = new Rng(9100 + $ci);
        $base = [];
        for ($i = 0; $i < 9; $i++) {
            $base[] = 1 + $rr2->range(-0.18, 0.18);
        }
        for ($k = 1; $k <= $n; $k++) {
            $pts = [];
            for ($i = 0; $i < 9; $i++) {
                $a     = 2 * M_PI * $i / 9 + $k * 0.05;
                $rad   = $k * 42 * $base[$i] * (1 + 0.04 * sin($k + $i));
                $pts[] = [$cx + $rad * cos($a), $cy + $rad * sin($a) * 0.72];
            }
            $topo .= el('path', ['d' => smooth($pts, true)]);
        }
    }
    $b .= el('g', ['fill' => 'none', 'stroke' => $c['300'], 'stroke-width' => 1.3, 'opacity' => '.14'], $topo);

    return [$defs, $b];
}

function bg_gold(Rng $r): array
{
    $c    = PAL['gold'];
    $tile = rr(0, 0, 80, 80, 0, $c['50'])
        . el('path', ['d' => 'M0 80A80 80 0 0 1 80 0V80Z', 'fill' => $c['100']])
        . el('path', ['d' => 'M80 80A40 40 0 0 0 40 40A40 40 0 0 0 0 80Z', 'fill' => $c['200'], 'opacity' => '.35']);
    $tile2 = rr(0, 0, 80, 80, 0, $c['50'])
        . el('path', ['d' => 'M0 0H80L0 80Z', 'fill' => $c['100']])
        . circ(56, 56, 12, $c['200'], ['opacity' => '.45']);
    $defs = el('pattern', ['id' => 'p', 'width' => 160, 'height' => 160, 'patternUnits' => 'userSpaceOnUse'],
        $tile . el('g', ['transform' => 'translate(80 0)'], $tile2) . el('g', ['transform' => 'translate(0 80)'], $tile2) . el('g', ['transform' => 'translate(80 80)'], $tile))
        . lin('fade', [[0, '#fffbeb', 0.45], [1, '#fffbeb', 0.85]], 0, 0, 1, 0);
    $b = rr(0, 0, 1600, 900, 0, 'url(#p)') . rr(0, 0, 1600, 900, 0, 'url(#fade)');

    return [$defs, $b];
}

function bg_sunset(Rng $r): array
{
    $defs = lin('bg', [[0, '#3a0d1f'], [0.5, '#6b1d24'], [1, '#9a3412']], 0, 0, 1, 1)
        . glowDef('g1', '#f97316', 0.35) . glowDef('g2', '#e11d48', 0.3);
    $b = rr(0, 0, 1600, 900, 0, 'url(#bg)') . circ(1500, 900, 700, 'url(#g1)') . circ(200, 0, 600, 'url(#g2)');

    return [$defs, $b];
}

// ---------------------------------------------------------------------------
// CARD ILLUSTRATIONS (1200×900)
// ---------------------------------------------------------------------------

function cardBackdrop(Rng $r, array $c, string $bgA, string $bgB): array
{
    $defs = lin('bg', [[0, $bgA], [1, $bgB]], 0, 0, 1, 1) . shadowDef('sh', $c['900'], 0.16) . glowDef('gl', '#ffffff', 0.75);
    $b    = rr(0, 0, 1200, 900, 0, 'url(#bg)')
        . circ(600, 430, 420, 'url(#gl)')
        . el('path', ['d' => blob($r, 600, 450, 330, 8, 0.12), 'fill' => $c['200'], 'opacity' => '.55'])
        . dotGrid(90, 90, 6, 4, 22, 3, $c['300'], 0.7)
        . dotGrid(990, 700, 5, 5, 22, 3, $c['300'], 0.7);

    return [$defs, $b];
}

function card_blue(Rng $r): array
{
    $c = PAL['blue'];
    [$defs, $b] = cardBackdrop($r, $c, '#f3f8ff', $c['100']);
    $defs .= lin('bar', [[0, $c['400']], [1, $c['700']]]) . lin('bar2', [[0, $c['acc']], [1, $c['500']]]);
    $b .= el('ellipse', ['cx' => 600, 'cy' => 720, 'rx' => 330, 'ry' => 22, 'fill' => $c['900'], 'opacity' => '.08']);
    $b .= rr(270, 220, 620, 470, 30, '#ffffff', ['filter' => 'url(#sh)']);
    $b .= circ(312, 262, 8, '#f87171') . circ(338, 262, 8, '#fbbf24') . circ(364, 262, 8, '#34d399');
    $b .= rr(310, 300, 190, 18, 9, $c['900'], ['opacity' => '.85']) . rr(310, 330, 120, 12, 6, $c['300']);
    // Grid lines.
    $grid = '';
    foreach ([420, 480, 540, 600] as $y) {
        $grid .= 'M310 ' . $y . 'H850';
    }
    $b .= el('path', ['d' => $grid, 'stroke' => $c['100'], 'stroke-width' => 2]);
    $heights = [110, 170, 130, 210, 175, 250];
    $pts     = [];
    foreach ($heights as $i => $h) {
        $x   = 350 + $i * 86;
        $b  .= rr($x, 640 - $h, 50, $h, 10, $i === 5 ? 'url(#bar2)' : 'url(#bar)');
        $pts[] = [$x + 25.0, 640 - $h - 46.0 - ($i % 2) * 10];
    }
    $b .= el('path', ['d' => smooth($pts), 'fill' => 'none', 'stroke' => $c['acc2'], 'stroke-width' => 6, 'stroke-linecap' => 'round']);
    foreach ($pts as $p) {
        $b .= circ($p[0], $p[1], 9, '#ffffff', ['stroke' => $c['acc2'], 'stroke-width' => 5]);
    }
    // Donut card.
    $b .= rr(790, 140, 280, 210, 26, '#ffffff', ['filter' => 'url(#sh)']);
    $b .= circ(880, 245, 58, 'none', ['stroke' => $c['100'], 'stroke-width' => 24]);
    $b .= circ(880, 245, 58, 'none', ['stroke' => $c['600'], 'stroke-width' => 24, 'stroke-dasharray' => '255 400', 'transform' => 'rotate(-90 880 245)', 'stroke-linecap' => 'round']);
    $b .= rr(960, 205, 80, 14, 7, $c['900'], ['opacity' => '.8']) . rr(960, 232, 60, 10, 5, $c['300']) . rr(960, 258, 70, 10, 5, $c['200']);
    // KPI pill.
    $b .= rr(110, 590, 230, 120, 24, '#ffffff', ['filter' => 'url(#sh)']);
    $b .= circ(166, 650, 32, '#dcfce7') . el('path', ['d' => 'M152 662L166 642L180 662M166 642V670', 'stroke' => '#16a34a', 'stroke-width' => 6, 'fill' => 'none', 'stroke-linecap' => 'round', 'stroke-linejoin' => 'round']);
    $b .= rr(214, 628, 100, 18, 9, $c['900'], ['opacity' => '.85']) . rr(214, 658, 70, 12, 6, '#86efac');
    $b .= sparkle(1060, 470, 18, $c['acc2']) . plus(160, 400, 14, $c['400'], 6);

    return [$defs, $b];
}

function card_purple(Rng $r): array
{
    $c = PAL['purple'];
    [$defs, $b] = cardBackdrop($r, $c, '#faf7ff', $c['100']);
    $defs .= lin('scr', [[0, $c['50']], [1, $c['100']]]) . lin('hero', [[0, $c['500']], [1, $c['acc']]], 0, 0, 1, 1) . lin('base', [[0, $c['300']], [1, $c['400']]]);
    $b .= el('ellipse', ['cx' => 600, 'cy' => 712, 'rx' => 420, 'ry' => 22, 'fill' => $c['900'], 'opacity' => '.08']);
    // Laptop.
    $b .= rr(270, 190, 580, 380, 26, $c['950'], ['filter' => 'url(#sh)']);
    $b .= rr(292, 212, 536, 336, 10, 'url(#scr)');
    $b .= rr(292, 212, 536, 40, 0, '#ffffff') . circ(318, 232, 7, $c['300']) . rr(700, 225, 100, 14, 7, $c['200']);
    $b .= rr(316, 272, 300, 150, 14, 'url(#hero)');
    $b .= rr(340, 300, 170, 16, 8, '#ffffff', ['opacity' => '.95']) . rr(340, 328, 120, 12, 6, '#ffffff', ['opacity' => '.7']) . rr(340, 372, 90, 28, 14, '#ffffff');
    $b .= rr(632, 272, 172, 150, 14, '#ffffff') . circ(718, 330, 34, $c['200']) . rr(670, 382, 96, 12, 6, $c['300']);
    foreach ([0, 1, 2] as $i) {
        $x  = 316 + $i * 168;
        $b .= rr($x, 440, 152, 88, 12, '#ffffff') . rr($x + 16, 458, 40, 40, 10, [$c['300'], '#fbcfe8', '#a5f3fc'][$i]) . rr($x + 68, 466, 66, 10, 5, $c['200']) . rr($x + 68, 484, 46, 8, 4, $c['100']);
    }
    $b .= el('path', ['d' => 'M220 570H900L948 618Q952 634 934 634H186Q168 634 172 618Z', 'fill' => 'url(#base)']);
    $b .= rr(520, 570, 80, 12, 6, $c['500'], ['opacity' => '.5']);
    // Phone.
    $b .= rr(830, 330, 180, 340, 30, $c['950'], ['filter' => 'url(#sh)']);
    $b .= rr(843, 344, 154, 312, 20, '#ffffff');
    $b .= rr(895, 352, 50, 10, 5, $c['950']);
    $b .= rr(858, 380, 124, 96, 12, 'url(#hero)') . rr(858, 490, 90, 12, 6, $c['400']) . rr(858, 512, 120, 10, 5, $c['200']) . rr(858, 530, 100, 10, 5, $c['200']);
    $b .= rr(858, 560, 124, 34, 17, $c['600']) . rr(858, 606, 124, 34, 17, $c['100']);
    // Little plant.
    $b .= el('path', ['d' => 'M100 560C70 500 90 450 130 430C136 480 126 520 100 560Z', 'fill' => '#34d399']);
    $b .= el('path', ['d' => 'M110 560C130 490 180 470 212 470C196 520 160 552 110 560Z', 'fill' => '#10b981']);
    $b .= el('path', ['d' => 'M72 560H160L150 634H82Z', 'fill' => $c['400']]);
    $b .= sparkle(1060, 250, 18, $c['acc']) . plus(980, 160, 12, $c['400'], 6);

    return [$defs, $b];
}

function card_teal(Rng $r): array
{
    $c = PAL['teal'];
    [$defs, $b] = cardBackdrop($r, $c, '#f2fdfa', $c['100']);
    $defs .= lin('sh1', [[0, $c['400']], [1, $c['700']]], 0, 0, 1, 1) . lin('sh2', [[0, '#ffffff', 0.35], [1, '#ffffff', 0]], 0, 0, 1, 0);
    $b .= el('circle', ['cx' => 600, 'cy' => 440, 'r' => 300, 'fill' => 'none', 'stroke' => $c['300'], 'stroke-width' => 3, 'stroke-dasharray' => '4 14', 'stroke-linecap' => 'round']);
    $b .= el('circle', ['cx' => 600, 'cy' => 440, 'r' => 230, 'fill' => 'none', 'stroke' => $c['300'], 'stroke-width' => 2, 'opacity' => '.7']);
    $b .= el('ellipse', ['cx' => 600, 'cy' => 740, 'rx' => 170, 'ry' => 20, 'fill' => $c['900'], 'opacity' => '.1']);
    $shield = 'M600 170L800 244C800 244 806 420 768 516C726 620 600 690 600 690C600 690 474 620 432 516C394 420 400 244 400 244Z';
    $b .= el('path', ['d' => $shield, 'fill' => 'url(#sh1)', 'filter' => 'url(#sh)']);
    $b .= el('path', ['d' => 'M600 170L400 244C400 244 394 420 432 516C474 620 600 690 600 690Z', 'fill' => 'url(#sh2)']);
    $b .= el('path', ['d' => 'M600 222L756 280C756 280 760 420 730 496C698 578 600 634 600 634C600 634 502 578 470 496C440 420 444 280 444 280Z', 'fill' => 'none', 'stroke' => '#ffffff', 'stroke-opacity' => '.35', 'stroke-width' => 4]);
    $b .= el('path', ['d' => 'M520 440L582 500L694 384', 'fill' => 'none', 'stroke' => '#ffffff', 'stroke-width' => 38, 'stroke-linecap' => 'round', 'stroke-linejoin' => 'round']);
    // Orbiting badges.
    foreach ([[360, 290, 'lock'], [858, 560, 'check'], [880, 250, 'dot']] as [$x, $y, $kind]) {
        $b .= circ($x, $y, 44, '#ffffff', ['filter' => 'url(#sh)']);
        if ($kind === 'lock') {
            $b .= rr($x - 18, $y - 4, 36, 28, 6, $c['600']) . el('path', ['d' => 'M' . ($x - 11) . ' ' . ($y - 4) . 'V' . ($y - 12) . 'A11 11 0 0 1 ' . ($x + 11) . ' ' . ($y - 12) . 'V' . ($y - 4), 'fill' => 'none', 'stroke' => $c['600'], 'stroke-width' => 6]);
        } elseif ($kind === 'check') {
            $b .= circ($x, $y, 24, $c['acc']) . el('path', ['d' => 'M' . ($x - 10) . ' ' . $y . 'L' . ($x - 2) . ' ' . ($y + 8) . 'L' . ($x + 12) . ' ' . ($y - 8), 'fill' => 'none', 'stroke' => '#ffffff', 'stroke-width' => 6, 'stroke-linecap' => 'round', 'stroke-linejoin' => 'round']);
        } else {
            $b .= circ($x, $y, 14, $c['acc2']);
        }
    }
    $b .= sparkle(300, 600, 16, $c['500']) . plus(980, 420, 12, $c['400'], 6);

    return [$defs, $b];
}

function card_sunset(Rng $r): array
{
    $c = PAL['sunset'];
    [$defs, $b] = cardBackdrop($r, $c, '#fffaf5', $c['100']);
    $defs .= lin('body', [[0, '#ffffff'], [1, '#ffe8d6']], 0, 0, 1, 0) . lin('fl', [[0, '#fde047'], [1, $c['500']]]) . lin('fin', [[0, $c['acc']], [1, '#be123c']]);
    // Trail.
    $b .= el('path', ['d' => 'M200 820C330 760 380 660 470 600', 'fill' => 'none', 'stroke' => $c['300'], 'stroke-width' => 6, 'stroke-dasharray' => '2 18', 'stroke-linecap' => 'round']);
    // Clouds.
    $cloud = static fn (float $x, float $y, float $s, float $op): string => el('g', ['fill' => '#ffffff', 'opacity' => $op],
        circ($x, $y, 46 * $s, '#ffffff') . circ($x + 52 * $s, $y - 22 * $s, 60 * $s, '#ffffff') . circ($x + 116 * $s, $y, 48 * $s, '#ffffff') . rr($x - 20 * $s, $y, 170 * $s, 46 * $s, 23 * $s, '#ffffff'));
    $b .= $cloud(200, 720, 1.1, 1) . $cloud(860, 640, 0.8, 0.9) . $cloud(160, 300, 0.6, 0.85);
    // Rocket, drawn upright then tilted.
    $rk  = el('path', ['d' => 'M-40 150C-40 210 0 280 0 300C0 280 40 210 40 150Z', 'fill' => 'url(#fl)']);
    $rk .= el('path', ['d' => 'M-20 150C-20 190 0 230 0 244C0 230 20 190 20 150Z', 'fill' => '#fff7ed']);
    $rk .= el('path', ['d' => 'M-80 40L-150 150L-150 180L-78 140Z', 'fill' => 'url(#fin)']);
    $rk .= el('path', ['d' => 'M80 40L150 150L150 180L78 140Z', 'fill' => 'url(#fin)']);
    $rk .= rr(-52, 124, 104, 34, 10, '#64748b');
    $rk .= el('path', ['d' => 'M0 -250C80 -190 96 -70 84 130H-84C-96 -70 -80 -190 0 -250Z', 'fill' => 'url(#body)', 'filter' => 'url(#sh)']);
    $rk .= el('path', ['d' => 'M0 -250C46 -215 70 -170 80 -122H-80C-70 -170 -46 -215 0 -250Z', 'fill' => 'url(#fin)']);
    $rk .= circ(0, -30, 44, $c['700']) . circ(0, -30, 32, '#1e293b') . el('path', ['d' => 'M-16 -46A22 22 0 0 1 10 -54', 'stroke' => '#ffffff', 'stroke-width' => 6, 'fill' => 'none', 'stroke-linecap' => 'round', 'opacity' => '.8']);
    $rk .= el('path', ['d' => 'M-6 140V40', 'stroke' => $c['200'], 'stroke-width' => 8, 'stroke-linecap' => 'round']);
    $b  .= el('g', ['transform' => 'translate(640 420) rotate(38)'], $rk);
    $b  .= sparkle(940, 220, 22, $c['500']) . sparkle(1030, 330, 12, $c['acc']) . sparkle(300, 160, 14, $c['400']) . plus(820, 140, 12, $c['400'], 6);
    $b  .= circ(1000, 470, 8, $c['300']) . circ(240, 480, 10, $c['acc'], ['opacity' => '.6']);

    return [$defs, $b];
}

function card_forest(Rng $r): array
{
    $c = PAL['forest'];
    [$defs, $b] = cardBackdrop($r, $c, '#f4fdf6', $c['100']);
    $defs .= lin('lf', [[0, $c['400']], [1, $c['700']]], 0, 0, 1, 1) . lin('lf2', [[0, $c['300']], [1, $c['600']]], 1, 0, 0, 1)
        . lin('pot', [[0, '#e7a17a'], [1, '#c2410c']]) . glowDef('sun', '#fde047', 0.75);
    $b .= circ(860, 230, 170, 'url(#sun)') . circ(860, 230, 64, '#fde68a');
    $b .= el('ellipse', ['cx' => 600, 'cy' => 780, 'rx' => 220, 'ry' => 22, 'fill' => $c['900'], 'opacity' => '.1']);
    $leaf = static function (float $x, float $y, float $len, float $wid, float $ang, string $fill): string {
        $d = 'M0 0C' . f($wid) . ' ' . f(-$len * 0.25) . ' ' . f($wid * 0.9) . ' ' . f(-$len * 0.8) . ' 0 ' . f(-$len)
            . 'C' . f(-$wid * 0.9) . ' ' . f(-$len * 0.8) . ' ' . f(-$wid) . ' ' . f(-$len * 0.25) . ' 0 0Z';
        $v = 'M0 -6V' . f(-$len * 0.92);
        for ($k = 1; $k <= 4; $k++) {
            $yy = -$len * (0.18 * $k);
            $v .= 'M0 ' . f($yy) . 'Q' . f($wid * 0.35) . ' ' . f($yy - 14) . ' ' . f($wid * 0.62) . ' ' . f($yy - 40)
                . 'M0 ' . f($yy) . 'Q' . f(-$wid * 0.35) . ' ' . f($yy - 14) . ' ' . f(-$wid * 0.62) . ' ' . f($yy - 40);
        }

        return el('g', ['transform' => 'translate(' . f($x) . ' ' . f($y) . ') rotate(' . f($ang) . ')'],
            el('path', ['d' => $d, 'fill' => $fill]) . el('path', ['d' => $v, 'fill' => 'none', 'stroke' => '#ffffff', 'stroke-opacity' => '.45', 'stroke-width' => 4, 'stroke-linecap' => 'round']));
    };
    $b .= el('path', ['d' => 'M600 640C596 560 560 480 520 420M600 640C606 560 640 470 700 400M600 640V330', 'stroke' => $c['700'], 'stroke-width' => 10, 'fill' => 'none', 'stroke-linecap' => 'round']);
    $b .= $leaf(520, 430, 240, 95, -48, 'url(#lf2)') . $leaf(700, 410, 260, 100, 44, 'url(#lf)') . $leaf(600, 340, 230, 92, 0, 'url(#lf)');
    $b .= el('path', ['d' => 'M470 630H730L700 780Q696 790 684 790H516Q504 790 500 780Z', 'fill' => 'url(#pot)', 'filter' => 'url(#sh)']);
    $b .= rr(452, 610, 296, 46, 16, '#ea8a5c');
    $b .= circ(330, 290, 10, $c['400']) . circ(370, 250, 6, $c['300']) . sparkle(1000, 520, 18, '#facc15') . plus(220, 520, 12, $c['400'], 6);

    return [$defs, $b];
}

function card_gold(Rng $r): array
{
    $c = PAL['gold'];
    [$defs, $b] = cardBackdrop($r, $c, '#fffdf5', $c['100']);
    $defs .= rad('bulb', [[0, '#fffbe6'], [0.6, $c['200']], [1, $c['400']]], ['cx' => '.4', 'cy' => '.35', 'r' => '.75']) . glowDef('glow', '#fde047', 0.8) . lin('base', [[0, '#94a3b8'], [1, '#475569']], 0, 0, 1, 0);
    $b .= circ(600, 360, 330, 'url(#glow)');
    $rays = '';
    for ($i = 0; $i < 10; $i++) {
        $a = -M_PI + $i * M_PI / 9;
        if ($i === 0 || $i === 9) {
            $a += $i === 0 ? 0.25 : -0.25;
        }
        $rays .= 'M' . f(600 + 245 * cos($a)) . ' ' . f(360 + 245 * sin($a)) . 'L' . f(600 + 300 * cos($a)) . ' ' . f(360 + 300 * sin($a));
    }
    $b .= el('path', ['d' => $rays, 'stroke' => $c['500'], 'stroke-width' => 14, 'stroke-linecap' => 'round']);
    $b .= el('ellipse', ['cx' => 600, 'cy' => 770, 'rx' => 140, 'ry' => 18, 'fill' => $c['900'], 'opacity' => '.12']);
    $b .= el('path', ['d' => 'M600 170C708 170 790 252 790 358C790 430 750 476 720 512C702 534 696 556 696 580H504C504 556 498 534 480 512C450 476 410 430 410 358C410 252 492 170 600 170Z', 'fill' => 'url(#bulb)', 'filter' => 'url(#sh)', 'stroke' => $c['400'], 'stroke-width' => 4]);
    $b .= el('path', ['d' => 'M480 330C486 270 524 232 570 218', 'stroke' => '#ffffff', 'stroke-width' => 16, 'stroke-linecap' => 'round', 'fill' => 'none', 'opacity' => '.85']);
    $b .= el('path', ['d' => 'M556 580V470L530 420Q600 380 670 420L644 470V580', 'stroke' => $c['700'], 'stroke-width' => 8, 'fill' => 'none', 'stroke-linejoin' => 'round']);
    $b .= rr(510, 580, 180, 34, 14, 'url(#base)') . rr(516, 620, 168, 30, 14, 'url(#base)') . rr(524, 656, 152, 30, 14, 'url(#base)');
    $b .= el('path', ['d' => 'M556 690H644Q644 730 600 734Q556 730 556 690Z', 'fill' => '#334155']);
    $b .= sparkle(900, 600, 20, $c['500']) . sparkle(290, 620, 14, $c['400']) . plus(940, 190, 12, $c['400'], 6);

    return [$defs, $b];
}

function card_rose(Rng $r): array
{
    $c = PAL['rose'];
    [$defs, $b] = cardBackdrop($r, $c, '#fff8f9', $c['100']);
    $defs .= lin('ra', [[0, $c['400']], [1, $c['700']]], 0, 0, 1, 1) . lin('rb', [[0, '#e879f9'], [1, '#9333ea']], 1, 0, 0, 1)
        . el('clipPath', ['id' => 'ov'], circ(600, 323, 82, '#000'));
    $ringA = el('circle', ['cx' => 515, 'cy' => 450, 'r' => 150, 'fill' => 'none', 'stroke' => 'url(#ra)', 'stroke-width' => 58]);
    $ringB = el('circle', ['cx' => 685, 'cy' => 450, 'r' => 150, 'fill' => 'none', 'stroke' => 'url(#rb)', 'stroke-width' => 58]);
    $b .= el('ellipse', ['cx' => 600, 'cy' => 700, 'rx' => 280, 'ry' => 20, 'fill' => $c['900'], 'opacity' => '.1']);
    $b .= el('g', ['filter' => 'url(#sh)'], $ringA . $ringB);
    $b .= el('g', ['clip-path' => 'url(#ov)'], $ringA);
    // Highlights.
    $b .= el('path', ['d' => 'M410 360A130 130 0 0 1 480 312', 'stroke' => '#ffffff', 'stroke-opacity' => '.55', 'stroke-width' => 12, 'fill' => 'none', 'stroke-linecap' => 'round']);
    $b .= el('path', ['d' => 'M790 540A130 130 0 0 1 740 590', 'stroke' => '#ffffff', 'stroke-opacity' => '.4', 'stroke-width' => 12, 'fill' => 'none', 'stroke-linecap' => 'round']);
    // Connection nodes.
    $b .= el('path', ['d' => 'M220 250Q300 220 360 300M980 650Q900 690 840 610', 'stroke' => $c['300'], 'stroke-width' => 5, 'fill' => 'none', 'stroke-dasharray' => '2 14', 'stroke-linecap' => 'round']);
    $b .= circ(210, 250, 34, '#ffffff', ['filter' => 'url(#sh)']) . circ(210, 250, 16, $c['500']);
    $b .= circ(990, 650, 34, '#ffffff', ['filter' => 'url(#sh)']) . circ(990, 650, 16, '#a855f7');
    $heart = 'M600 230C600 230 572 200 552 214C532 228 540 254 600 290C660 254 668 228 648 214C628 200 600 230 600 230Z';
    $b .= el('path', ['d' => $heart, 'fill' => $c['500'], 'transform' => 'translate(0 -40)']);
    $b .= sparkle(960, 230, 18, $c['acc2']) . plus(260, 640, 12, $c['400'], 6) . sparkle(870, 790, 10, $c['400']);

    return [$defs, $b];
}

function card_slate(Rng $r): array
{
    $c = PAL['slate'];
    [$defs, $b] = cardBackdrop($r, $c, $c['50'], $c['200']);
    $defs .= lin('pin', [[0, '#fb7185'], [1, '#be123c']], 0, 0, 1, 1)
        . el('clipPath', ['id' => 'map'], el('path', ['d' => 'M220 330L440 260L660 330L900 260V640L660 710L440 640L220 710Z']));
    $b .= el('path', ['d' => 'M220 330L440 260L660 330L900 260V640L660 710L440 640L220 710Z', 'fill' => '#ffffff', 'filter' => 'url(#sh)']);
    $m  = el('path', ['d' => 'M440 260L660 330V710L440 640Z', 'fill' => $c['100']]);
    $m .= el('path', ['d' => blob($r, 330, 450, 80, 6, 0.2), 'fill' => '#bbf7d0']) . el('path', ['d' => blob($r, 780, 600, 70, 6, 0.2), 'fill' => '#bbf7d0']);
    $m .= el('path', ['d' => 'M200 600C320 560 380 640 500 580C620 520 640 420 760 420C820 420 880 380 920 360', 'stroke' => '#93c5fd', 'stroke-width' => 26, 'fill' => 'none']);
    $m .= el('path', ['d' => 'M200 420H940M340 250V720M560 250V720M200 520L940 340', 'stroke' => $c['300'], 'stroke-width' => 10, 'fill' => 'none']);
    $m .= el('path', ['d' => 'M660 330V710M440 260V640', 'stroke' => $c['900'], 'stroke-opacity' => '.06', 'stroke-width' => 6]);
    $b .= el('g', ['clip-path' => 'url(#map)'], $m);
    $b .= el('path', ['d' => 'M300 640C380 600 400 520 480 520S600 560 620 470', 'stroke' => $c['acc'], 'stroke-width' => 8, 'fill' => 'none', 'stroke-dasharray' => '4 16', 'stroke-linecap' => 'round']);
    $b .= circ(300, 640, 14, '#ffffff', ['stroke' => $c['acc'], 'stroke-width' => 7]);
    $b .= el('ellipse', ['cx' => 620, 'cy' => 470, 'rx' => 60, 'ry' => 16, 'fill' => $c['900'], 'opacity' => '.2']);
    $b .= el('path', ['d' => 'M620 470C620 470 500 340 500 250A120 120 0 1 1 740 250C740 340 620 470 620 470Z', 'fill' => 'url(#pin)', 'filter' => 'url(#sh)']);
    $b .= circ(620, 250, 46, '#ffffff') . circ(620, 250, 20, $c['acc2'], ['opacity' => '.35']);
    $b .= sparkle(900, 170, 18, $c['acc']) . plus(240, 200, 12, $c['400'], 6);

    return [$defs, $b];
}

// ---------------------------------------------------------------------------
// SQUARES (800×800) — gallery / feature graphics.
// ---------------------------------------------------------------------------

function sq_slate(Rng $r): array
{
    $c    = PAL['slate'];
    $defs = lin('bg', [[0, $c['100']], [1, $c['300']]], 0, 0, 1, 1) . lin('a', [[0, $c['500']], [1, $c['700']]], 0, 0, 1, 1) . lin('b', [[0, '#ffffff'], [1, $c['200']]], 0, 0, 1, 1)
        . shadowDef('sh', $c['900'], 0.18, 14, 18);
    $b = rr(0, 0, 800, 800, 0, 'url(#bg)');
    $b .= el('g', ['filter' => 'url(#sh)'],
        circ(320, 330, 190, 'url(#a)')
        . rr(380, 360, 260, 260, 28, 'url(#b)')
        . el('path', ['d' => 'M150 650A150 150 0 0 1 450 650Z', 'fill' => $c['400']]));
    $b .= circ(510, 490, 62, $c['acc']);
    $b .= el('path', ['d' => 'M560 150A110 110 0 0 1 670 260', 'stroke' => $c['600'], 'stroke-width' => 22, 'fill' => 'none', 'stroke-linecap' => 'round']);
    $b .= dotGrid(110, 110, 4, 4, 22, 4, $c['500'], 0.5);
    $b .= el('path', ['d' => 'M580 680L630 630L680 680L730 630', 'stroke' => $c['600'], 'stroke-width' => 10, 'fill' => 'none', 'stroke-linecap' => 'round', 'stroke-linejoin' => 'round']);

    return [$defs, $b];
}

function sq_blue(Rng $r): array
{
    $c    = PAL['blue'];
    $defs = lin('sky', [[0, $c['950']], [0.6, $c['800']], [1, $c['600']]]) . glowDef('moon', '#e0f2fe', 0.55);
    $b    = rr(0, 0, 800, 800, 0, 'url(#sky)');
    for ($i = 0; $i < 40; $i++) {
        $b .= circ($r->range(0, 800), $r->range(0, 420), $r->range(0.8, 2.2), '#ffffff', ['opacity' => $r->range(0.3, 0.9)]);
    }
    $b .= circ(560, 250, 200, 'url(#moon)') . circ(560, 250, 74, '#f0f9ff') . circ(536, 232, 14, '#dbeafe') . circ(588, 276, 10, '#dbeafe');
    $layers = [[500, 26, $c['700'], 0.9], [560, 24, $c['800'], 0.95], [630, 20, '#152c6e', 1], [710, 16, $c['900'], 1]];
    foreach ($layers as $i => [$y, $amp, $col, $op]) {
        $b .= el('path', ['d' => waveArea(wavePoints(-20, 820, $y, $amp, 320 + $i * 40, $i * 1.3, 10), 800), 'fill' => $col, 'opacity' => $op]);
    }
    $b .= el('path', ['d' => 'M520 520H600M500 560H620M530 600H590M545 650H575', 'stroke' => '#e0f2fe', 'stroke-opacity' => '.5', 'stroke-width' => 5, 'stroke-linecap' => 'round']);

    return [$defs, $b];
}

function sq_purple(Rng $r): array
{
    $c    = PAL['purple'];
    $defs = lin('bg', [[0, $c['950']], [1, $c['800']]], 0, 0, 1, 1) . glowDef('neb', $c['acc'], 0.35) . glowDef('neb2', $c['500'], 0.5)
        . lin('pl', [[0, '#fbcfe8'], [0.5, $c['400']], [1, $c['700']]], 0, 0, 1, 1)
        . lin('ring', [[0, '#ffffff', 0.1], [0.5, '#fde68a', 0.9], [1, '#ffffff', 0.1]], 0, 0, 1, 0);
    $b = rr(0, 0, 800, 800, 0, 'url(#bg)') . circ(160, 160, 360, 'url(#neb)') . circ(620, 640, 380, 'url(#neb2)');
    for ($i = 0; $i < 70; $i++) {
        $b .= circ($r->range(0, 800), $r->range(0, 800), $r->range(0.8, 2.4), '#ffffff', ['opacity' => $r->range(0.3, 0.9)]);
    }
    $ring = el('ellipse', ['cx' => 400, 'cy' => 400, 'rx' => 300, 'ry' => 62, 'fill' => 'none', 'stroke' => 'url(#ring)', 'stroke-width' => 18, 'transform' => 'rotate(-18 400 400)']);
    $b .= $ring;
    $b .= circ(400, 400, 170, 'url(#pl)');
    $b .= el('path', ['d' => 'M262 330C330 350 470 340 540 300M240 420C340 450 480 440 565 400', 'stroke' => '#ffffff', 'stroke-opacity' => '.18', 'stroke-width' => 18, 'fill' => 'none', 'stroke-linecap' => 'round']);
    // Front half of the ring (lower arc) over the planet.
    $b .= el('g', ['transform' => 'rotate(-18 400 400)'], el('path', ['d' => 'M100 400A300 62 0 0 0 700 400', 'fill' => 'none', 'stroke' => 'url(#ring)', 'stroke-width' => 18]));
    $b .= circ(650, 170, 26, '#fde68a') . circ(150, 640, 14, $c['300']);
    $b .= sparkle(660, 560, 16, '#ffffff', 0.9) . sparkle(130, 300, 10, '#ffffff', 0.7);

    return [$defs, $b];
}

function sq_teal(Rng $r): array
{
    $c    = PAL['teal'];
    $cols = [$c['900'], $c['600'], $c['300'], $c['100'], $c['acc'], $c['acc2'], $c['400']];
    $b    = rr(0, 0, 800, 800, 0, $c['50']);
    for ($j = 0; $j < 4; $j++) {
        for ($i = 0; $i < 4; $i++) {
            $x    = $i * 200;
            $y    = $j * 200;
            $bgc  = $cols[$r->int(0, 3)];
            $fgc  = $cols[$r->int(0, 6)];
            if ($fgc === $bgc) {
                $fgc = $c['50'];
            }
            $b   .= rr($x, $y, 200, 200, 0, $bgc);
            $kind = $r->int(0, 4);
            $rot  = 90 * $r->int(0, 3);
            $g    = match ($kind) {
                0 => el('path', ['d' => 'M0 200A200 200 0 0 1 200 0V200Z', 'fill' => $fgc]),
                1 => el('path', ['d' => 'M0 100A100 100 0 0 1 200 100Z', 'fill' => $fgc]),
                2 => circ(100, 100, 70, $fgc),
                3 => el('path', ['d' => 'M0 0H200L0 200Z', 'fill' => $fgc]),
                default => circ(100, 100, 70, 'none', ['stroke' => $fgc, 'stroke-width' => 26]),
            };
            $b .= el('g', ['transform' => 'translate(' . $x . ' ' . $y . ') rotate(' . $rot . ' 100 100)'], $g);
        }
    }

    return ['', $b];
}

function sq_sunset(Rng $r): array
{
    $c    = PAL['sunset'];
    $defs = lin('sky', [[0, '#fde68a'], [0.45, $c['300']], [1, '#f472b6']]) . lin('sun', [[0, '#fff7d6'], [1, '#fde047']]) . glowDef('g', '#fff7d6', 0.7);
    $b    = rr(0, 0, 800, 800, 0, 'url(#sky)') . circ(400, 420, 260, 'url(#g)') . circ(400, 420, 120, 'url(#sun)');
    // Mountain ranges: a few broad peaks per layer, alternating sides.
    $layers = [[470, 150, '#f6a07a', 0], [530, 130, '#e8746a', 1], [600, 110, '#c2456a', 0], [670, 80, '#8f2f5e', 1], [740, 50, '#5b1f4f', 0]];
    foreach ($layers as [$y, $hgt, $col, $flip]) {
        $pts = [];
        for ($k = 0; $k <= 4; $k++) {
            $peak  = ($k + $flip) % 2 === 1;
            $pts[] = [-60 + $k * 230.0 + $r->range(-30, 30), $peak ? $y - $hgt * $r->range(0.7, 1.0) : $y + $r->range(0, 20)];
        }
        $b .= el('path', ['d' => waveArea($pts, 800), 'fill' => $col]);
    }
    $b .= el('path', ['d' => 'M200 210q14-14 28 0q14-14 28 0M290 170q10-10 20 0q10-10 20 0', 'stroke' => '#7c2d12', 'stroke-width' => 4, 'fill' => 'none', 'stroke-linecap' => 'round', 'opacity' => '.6']);

    return [$defs, $b];
}

function sq_forest(Rng $r): array
{
    $c    = PAL['forest'];
    $defs = lin('bg', [[0, '#f0fdf4'], [1, '#d9f5e3']]) . lin('lf', [[0, $c['400']], [1, $c['700']]], 0, 0, 1, 1) . lin('lf2', [[0, $c['500']], [1, $c['800']]], 1, 0, 0, 1)
        . lin('pot', [[0, '#f5f0e8'], [1, '#d6cbbb']], 0, 0, 1, 0);
    $b = rr(0, 0, 800, 800, 0, 'url(#bg)') . circ(560, 260, 150, '#fef9c3') . rr(0, 640, 800, 160, 0, '#c8ecd4');
    $leafPath = static function (float $len, float $wid): string {
        return 'M0 0C' . f($wid) . ' ' . f(-$len * 0.3) . ' ' . f($wid * 0.8) . ' ' . f(-$len * 0.85) . ' 0 ' . f(-$len)
            . 'C' . f(-$wid * 0.8) . ' ' . f(-$len * 0.85) . ' ' . f(-$wid) . ' ' . f(-$len * 0.3) . ' 0 0Z';
    };
    $leaves = [[-62, 230, 80, 'url(#lf2)'], [-30, 270, 86, 'url(#lf)'], [0, 300, 90, 'url(#lf2)'], [28, 270, 86, 'url(#lf)'], [60, 230, 80, 'url(#lf2)'], [-88, 180, 66, 'url(#lf)'], [86, 180, 66, 'url(#lf)']];
    foreach ($leaves as [$ang, $len, $wid, $fill]) {
        $b .= el('g', ['transform' => 'translate(400 520) rotate(' . $ang . ')'],
            el('path', ['d' => $leafPath($len, $wid), 'fill' => $fill])
            . el('path', ['d' => 'M0 -10V' . f(-$len * 0.9), 'stroke' => '#ffffff', 'stroke-opacity' => '.35', 'stroke-width' => 4, 'stroke-linecap' => 'round']));
    }
    $b .= el('path', ['d' => 'M290 520H510L486 690Q482 700 470 700H330Q318 700 314 690Z', 'fill' => 'url(#pot)']);
    $b .= rr(276, 500, 248, 40, 14, '#ece5da') . el('path', ['d' => 'M300 600H500', 'stroke' => $c['600'], 'stroke-width' => 6, 'opacity' => '.5']);

    return [$defs, $b];
}

function sq_rose(Rng $r): array
{
    $c    = PAL['rose'];
    $defs = lin('bg', [[0, $c['50']], [1, $c['100']]], 0, 0, 1, 1) . lin('p1', [[0, $c['300']], [1, $c['500']]]) . lin('p2', [[0, $c['400']], [1, $c['700']]]) . rad('cn', [[0, '#fde68a'], [1, '#f59e0b']]);
    $b    = rr(0, 0, 800, 800, 0, 'url(#bg)');
    $b   .= el('path', ['d' => blob($r, 400, 400, 330, 9, 0.08), 'fill' => '#ffffff', 'opacity' => '.6']);
    $petals = static function (int $n, float $len, float $wid, string $fill, float $off): string {
        $o = '';
        for ($i = 0; $i < $n; $i++) {
            $a  = $off + 360 * $i / $n;
            $o .= el('ellipse', ['cx' => 400, 'cy' => f(400 - $len / 2), 'rx' => $wid, 'ry' => f($len / 2), 'fill' => $fill, 'transform' => 'rotate(' . f($a) . ' 400 400)']);
        }

        return $o;
    };
    $b .= $petals(12, 300, 52.0, 'url(#p1)', 0) . $petals(12, 220, 44.0, 'url(#p2)', 15) . $petals(8, 140, 34.0, $c['300'], 0);
    $b .= circ(400, 400, 56, 'url(#cn)');
    for ($i = 0; $i < 10; $i++) {
        $a  = 2 * M_PI * $i / 10;
        $b .= circ(400 + 32 * cos($a), 400 + 32 * sin($a), 5, '#b45309', ['opacity' => '.6']);
    }
    $b .= sparkle(680, 130, 18, $c['500']) . sparkle(120, 680, 14, $c['400']);

    return [$defs, $b];
}

function sq_gold(Rng $r): array
{
    $c    = PAL['gold'];
    $defs = lin('bg', [[0, '#fef7e6'], [1, $c['100']]], 0, 0, 1, 1) . lin('cup', [[0, '#ffffff'], [1, '#efe7da']], 0, 0, 1, 0) . lin('cof', [[0, '#7c4a1e'], [1, '#4a2a0f']]);
    $b    = rr(0, 0, 800, 800, 0, 'url(#bg)') . circ(400, 420, 290, $c['200'], ['opacity' => '.55']);
    $b   .= el('ellipse', ['cx' => 400, 'cy' => 610, 'rx' => 250, 'ry' => 46, 'fill' => '#e9dcc6']) . el('ellipse', ['cx' => 400, 'cy' => 600, 'rx' => 250, 'ry' => 46, 'fill' => '#ffffff']);
    $b   .= el('ellipse', ['cx' => 400, 'cy' => 598, 'rx' => 150, 'ry' => 24, 'fill' => '#efe7da']);
    $b   .= el('path', ['d' => 'M545 400C640 390 650 520 548 520', 'stroke' => '#efe7da', 'stroke-width' => 30, 'fill' => 'none']);
    $b   .= el('path', ['d' => 'M230 380H570C570 500 520 600 400 600C280 600 230 500 230 380Z', 'fill' => 'url(#cup)']);
    $b   .= el('ellipse', ['cx' => 400, 'cy' => 380, 'rx' => 170, 'ry' => 36, 'fill' => '#ffffff']);
    $b   .= el('ellipse', ['cx' => 400, 'cy' => 384, 'rx' => 150, 'ry' => 26, 'fill' => 'url(#cof)']);
    $b   .= el('path', ['d' => 'M370 380Q400 360 430 380Q400 400 370 380Z', 'fill' => '#e8c9a0', 'opacity' => '.8']);
    $b   .= el('path', ['d' => 'M340 320C320 280 360 250 340 200M400 310C380 260 425 230 400 170M460 320C440 280 480 250 460 200', 'stroke' => '#ffffff', 'stroke-width' => 12, 'fill' => 'none', 'stroke-linecap' => 'round', 'opacity' => '.85']);
    $b   .= rr(280, 450, 240, 10, 5, $c['500'], ['opacity' => '.5']);
    $b   .= sparkle(650, 180, 16, $c['500']) . plus(150, 200, 12, $c['400'], 6);

    return [$defs, $b];
}

// ---------------------------------------------------------------------------
// AVATARS (400×400) — friendly illustrated people, clearly not photographs.
// ---------------------------------------------------------------------------

/** @param array{bg:string,ring:string,skin:string,shade:string,hair:string,shirt:string,style:string,glasses?:bool,beard?:bool} $o */
function avatar(array $o): array
{
    $skin  = $o['skin'];
    $shade = $o['shade'];
    $hair  = $o['hair'];
    $defs  = lin('bg', [[0, $o['bg']], [1, $o['ring']]], 0, 0, 1, 1);
    $bg    = rr(0, 0, 400, 400, 0, 'url(#bg)') . circ(200, 214, 160, '#ffffff', ['opacity' => '.35']);
    $b     = '';

    $back  = '';
    $front = '';
    switch ($o['style']) {
        case 'short':
            $front = el('path', ['d' => 'M128 196C118 126 158 92 206 94C254 96 286 132 272 198C268 172 258 154 244 146C220 160 176 158 146 150C138 164 132 180 128 196Z', 'fill' => $hair]);
            break;
        case 'long':
            $back  = el('path', ['d' => 'M110 330C88 220 106 92 200 88C294 92 312 220 290 330C262 346 138 346 110 330Z', 'fill' => $hair]);
            $front = el('path', ['d' => 'M128 200C120 128 158 94 204 94C250 96 284 130 274 204C262 166 236 138 196 132C172 150 150 170 128 200Z', 'fill' => $hair]);
            break;
        case 'curly':
            $curls = '';
            for ($i = 0; $i < 13; $i++) {
                $a      = M_PI * (0.95 + 1.1 * $i / 12);
                $curls .= circ(200 + 92 * cos($a), 170 + 86 * sin($a), 34, $hair);
            }
            $back  = el('ellipse', ['cx' => 200, 'cy' => 160, 'rx' => 110, 'ry' => 96, 'fill' => $hair]) . $curls;
            $front = el('path', ['d' => 'M130 176C128 120 162 94 200 94C238 94 272 120 270 176C250 154 226 146 200 146C174 146 150 154 130 176Z', 'fill' => $hair]);
            break;
        case 'bun':
            $back  = circ(200, 82, 40, $hair);
            $front = el('path', ['d' => 'M128 198C120 128 158 98 202 98C248 98 282 128 272 198C262 160 236 132 200 128C164 132 138 160 128 198Z', 'fill' => $hair]);
            break;
        case 'bob':
            $back  = el('path', ['d' => 'M114 262C96 156 136 88 200 88C264 88 304 156 286 262C270 270 130 270 114 262Z', 'fill' => $hair]);
            $front = el('path', ['d' => 'M130 182C130 126 164 100 200 100C236 100 270 126 270 182C246 160 222 150 200 150C174 150 152 160 130 182Z', 'fill' => $hair]);
            break;
        case 'bald':
            $front = el('path', ['d' => 'M132 200C128 180 130 166 136 152C140 170 140 186 140 204ZM268 200C272 180 270 166 264 152C260 170 260 186 260 204Z', 'fill' => $hair]);
            break;
        case 'scarf':
            $back  = el('path', ['d' => 'M200 76C116 76 92 160 100 236C106 300 132 326 200 332C268 326 294 300 300 236C308 160 284 76 200 76Z', 'fill' => $hair]);
            $front = el('path', ['d' => 'M134 160C150 116 176 104 200 104C224 104 250 116 266 160C246 140 224 134 200 134C176 134 154 140 134 160Z', 'fill' => $hair])
                . el('path', ['d' => 'M146 128C168 112 232 112 254 128', 'stroke' => '#ffffff', 'stroke-opacity' => '.25', 'stroke-width' => 6, 'fill' => 'none', 'stroke-linecap' => 'round']);
            break;
        case 'pony':
            $back  = el('path', ['d' => 'M262 140C320 150 330 240 300 300C296 250 280 210 256 190Z', 'fill' => $hair]);
            $front = el('path', ['d' => 'M128 198C118 128 158 94 204 94C250 96 284 130 272 196C258 156 226 128 172 136C150 152 136 172 128 198Z', 'fill' => $hair]);
            break;
    }

    $shirt = $o['shirt'];
    $body  = el('path', ['d' => 'M58 400C58 330 112 290 200 290C288 290 342 330 342 400Z', 'fill' => $shirt]);
    if ($o['style'] === 'scarf') {
        // The scarf wraps the head and neck and drapes over the shoulders.
        $b .= $body;
        $b .= el('path', ['d' => 'M104 236C110 300 128 336 112 400H288C272 336 290 300 296 236Z', 'fill' => $hair]);
        $b .= $back;
        $b .= el('path', ['d' => 'M150 318Q200 350 250 318', 'stroke' => '#ffffff', 'stroke-opacity' => '.18', 'stroke-width' => 6, 'fill' => 'none', 'stroke-linecap' => 'round']);
    } else {
        $b .= $back . $body;
        $b .= rr(172, 226, 56, 82, 24, $shade);
        $b .= el('path', ['d' => 'M168 290Q200 336 232 290Z', 'fill' => $shade]);
        $b .= el('path', ['d' => 'M160 292Q200 344 240 292', 'stroke' => '#ffffff', 'stroke-opacity' => '.35', 'stroke-width' => 6, 'fill' => 'none']);
    }
    if (!in_array($o['style'], ['scarf', 'bob', 'long'], true)) {
        $b .= el('ellipse', ['cx' => 130, 'cy' => 192, 'rx' => 14, 'ry' => 19, 'fill' => $skin]) . el('ellipse', ['cx' => 270, 'cy' => 192, 'rx' => 14, 'ry' => 19, 'fill' => $skin]);
    }
    $b .= el('ellipse', ['cx' => 200, 'cy' => 182, 'rx' => 70, 'ry' => 80, 'fill' => $skin]);
    // Face.
    $b .= circ(160, 218, 13, '#fb7185', ['opacity' => '.22']) . circ(240, 218, 13, '#fb7185', ['opacity' => '.22']);
    $b .= el('ellipse', ['cx' => 174, 'cy' => 192, 'rx' => 7, 'ry' => 8.5, 'fill' => '#1f2937']) . el('ellipse', ['cx' => 226, 'cy' => 192, 'rx' => 7, 'ry' => 8.5, 'fill' => '#1f2937']);
    $b .= circ(176.5, 189, 2.4, '#ffffff') . circ(228.5, 189, 2.4, '#ffffff');
    $brow = $o['style'] === 'scarf' ? '#3b2a20' : $hair;
    $b .= el('path', ['d' => 'M160 170Q174 162 188 168M212 168Q226 162 240 170', 'stroke' => $brow, 'stroke-width' => 5, 'fill' => 'none', 'stroke-linecap' => 'round']);
    $b .= el('path', ['d' => 'M200 198Q207 212 197 216', 'stroke' => $shade, 'stroke-width' => 4, 'fill' => 'none', 'stroke-linecap' => 'round']);
    if (!empty($o['beard'])) {
        $b .= el('path', ['d' => 'M131 192C134 266 168 292 200 292C232 292 266 266 269 192C258 222 238 236 224 234Q200 222 176 234C162 236 142 222 131 192Z', 'fill' => $hair]);
        $b .= el('path', ['d' => 'M182 240Q200 252 218 240', 'stroke' => '#ffffff', 'stroke-width' => 5, 'fill' => 'none', 'stroke-linecap' => 'round', 'opacity' => '.9']);
    } else {
        $b .= el('path', ['d' => 'M180 228Q200 248 220 228Z', 'fill' => '#9f1239']) . el('path', ['d' => 'M184 229H216', 'stroke' => '#ffffff', 'stroke-width' => 3]);
    }
    $b .= $front;
    if (!empty($o['glasses'])) {
        $b .= el('g', ['fill' => '#ffffff', 'fill-opacity' => '.15', 'stroke' => '#1f2937', 'stroke-width' => 5],
            rr(148, 174, 52, 38, 14, '#ffffff') . rr(200 + 2, 174, 52, 38, 14, '#ffffff'));
        $b .= el('path', ['d' => 'M196 186Q201 182 206 186', 'stroke' => '#1f2937', 'stroke-width' => 5, 'fill' => 'none']);
    }

    // Frame the figure a little tighter so it reads well in small circular crops.
    return [$defs, $bg . el('g', ['transform' => 'translate(-30 -34.5) scale(1.15)'], $b)];
}

// ---------------------------------------------------------------------------
// LOGOS (600×200) — abstract marks + wordmark bars, NO text, transparent bg.
// ---------------------------------------------------------------------------

function logoBars(float $x, string $ink, string $soft): string
{
    return rr($x, 74, 250, 30, 15, $ink) . rr($x, 118, 170, 14, 7, $soft);
}

function logo_1(Rng $r): array
{
    $c    = PAL['blue'];
    $defs = lin('m', [[0, $c['400']], [1, $c['700']]], 0, 0, 1, 1);
    $b    = rr(70, 40, 120, 120, 32, 'url(#m)') . sparkle(130, 100, 38, '#ffffff') . circ(158, 70, 7, '#ffffff', ['opacity' => '.7']);
    $b   .= logoBars(220, '#1e293b', '#94a3b8');

    return [$defs, $b];
}

function logo_2(Rng $r): array
{
    $c    = PAL['teal'];
    $defs = lin('m', [[0, $c['300']], [1, $c['700']]], 0, 0, 1, 1);
    $hex  = [];
    for ($i = 0; $i < 6; $i++) {
        $a     = M_PI / 6 + $i * M_PI / 3;
        $hex[] = f(130 + 64 * cos($a)) . ' ' . f(100 + 64 * sin($a));
    }
    $b  = el('polygon', ['points' => implode(' ', $hex), 'fill' => 'url(#m)', 'stroke' => 'url(#m)', 'stroke-width' => 10, 'stroke-linejoin' => 'round']);
    $b .= circ(130, 100, 24, '#ffffff') . circ(130, 100, 10, $c['600']);
    $b .= logoBars(220, '#134e4a', '#5eead4');

    return [$defs, $b];
}

function logo_3(Rng $r): array
{
    $c    = PAL['purple'];
    $defs = '';
    $b    = circ(130, 76, 38, '#fbbf24', ['opacity' => '.9']) . circ(109, 114, 38, $c['500'], ['opacity' => '.85']) . circ(151, 114, 38, $c['acc'], ['opacity' => '.85']);
    $b   .= logoBars(220, '#2e1065', '#c4b5fd');

    return [$defs, $b];
}

function logo_4(Rng $r): array
{
    $b  = el('path', ['d' => 'M70 150L130 50L190 150Z', 'fill' => 'none', 'stroke' => '#ffffff', 'stroke-width' => 14, 'stroke-linejoin' => 'round']);
    $b .= circ(130, 116, 18, '#ffffff');
    $b .= rr(220, 74, 250, 30, 15, '#ffffff') . rr(220, 118, 170, 14, 7, '#ffffff', ['opacity' => '.7']);

    return ['', $b];
}

// ---------------------------------------------------------------------------
// Catalogue
// ---------------------------------------------------------------------------

/** @return list<array{token:string,role:string,palette:string,w:int,h:int,tone:string,alt:string,fn:callable}> */
function catalogue(): array
{
    $list = [];
    $add  = static function (string $token, string $role, string $palette, int $w, int $h, string $tone, string $alt, callable $fn) use (&$list): void {
        $list[] = compact('token', 'role', 'palette', 'w', 'h', 'tone', 'alt', 'fn');
    };

    $heroes = [
        'blue'   => 'Dark blue abstract background with glowing gradients, fine flowing lines and layered waves',
        'purple' => 'Dark purple abstract background with a glowing pink-to-cyan aurora ribbon and stars',
        'teal'   => 'Dark teal abstract background with glowing concentric rings and orbiting dots',
        'sunset' => 'Dark retro sunset with a glowing striped sun over layered dunes',
        'forest' => 'Dark green layered mountain ridges in mist under a pale moon and stars',
        'slate'  => 'Dark slate tech background with a glowing perspective grid and floating glass panels',
        'rose'   => 'Dark rose abstract background with soft blurred pink and magenta shapes',
        'gold'   => 'Dark amber background with glowing gold bokeh, a light beam and fine arcs',
    ];
    foreach ($heroes as $p => $alt) {
        $add('hero-' . $p . '-1', 'hero', $p, 1600, 900, 'dark', $alt, 'hero_' . $p);
    }

    $bgs = [
        'slate'  => ['light', 'Light grey background with a subtle dot pattern fading towards the centre'],
        'blue'   => ['light', 'Very light blue background with a faint grid and soft glows'],
        'purple' => ['dark', 'Deep purple background with faint diagonal lines and a soft glow'],
        'teal'   => ['light', 'Very light mint background with thin flowing wave lines'],
        'rose'   => ['light', 'Very light pink background with soft blurred pastel blobs'],
        'forest' => ['dark', 'Deep green background with faint topographic contour lines'],
        'gold'   => ['light', 'Light cream background with a soft geometric tile pattern'],
        'sunset' => ['dark', 'Smooth dark plum-to-burnt-orange gradient with soft glows'],
    ];
    foreach ($bgs as $p => [$tone, $alt]) {
        $add('section-bg-' . $p . '-1', 'section-bg', $p, 1600, 900, $tone, $alt, 'bg_' . $p);
    }

    $cards = [
        'blue'   => 'Illustration of an analytics dashboard with bar, line and donut charts',
        'purple' => 'Illustration of a laptop and a phone showing a website, with a small plant',
        'teal'   => 'Illustration of a security shield with a check mark and lock badges',
        'sunset' => 'Illustration of a rocket launching through clouds',
        'forest' => 'Illustration of a green sprout with three leaves in a terracotta pot',
        'gold'   => 'Illustration of a glowing light bulb idea',
        'rose'   => 'Illustration of two interlocking rings with a heart, symbolising partnership',
        'slate'  => 'Illustration of a folded map with a dashed route and a red location pin',
    ];
    foreach ($cards as $p => $alt) {
        $add('card-' . $p . '-1', 'card', $p, 1200, 900, 'light', $alt, 'card_' . $p);
    }

    $squares = [
        'slate'  => ['light', 'Abstract composition of slate-grey circles, a square and arcs'],
        'blue'   => ['dark', 'Illustrated night sea with a full moon and layered blue waves'],
        'purple' => ['dark', 'Illustrated ringed planet in a purple starry sky'],
        'teal'   => ['dark', 'Geometric tile pattern of teal circles, arcs and triangles'],
        'sunset' => ['light', 'Illustrated sunset over layered pink and plum mountains'],
        'forest' => ['light', 'Illustrated potted plant with green leaves'],
        'rose'   => ['light', 'Illustrated pink flower with layered petals'],
        'gold'   => ['light', 'Illustrated cup of coffee with steam on a saucer'],
    ];
    foreach ($squares as $p => [$tone, $alt]) {
        $add('square-' . $p . '-1', 'square', $p, 800, 800, $tone, $alt, 'sq_' . $p);
    }

    $avatars = [
        ['blue', ['bg' => '#dbeafe', 'ring' => '#93c5fd', 'skin' => '#f6d3bd', 'shade' => '#e6b69b', 'hair' => '#3b2416', 'shirt' => '#2563eb', 'style' => 'short'], 'person with short dark-brown hair'],
        ['rose', ['bg' => '#ffe4e6', 'ring' => '#fda4af', 'skin' => '#8d5a3b', 'shade' => '#744528', 'hair' => '#1c120c', 'shirt' => '#e11d48', 'style' => 'curly'], 'person with curly black hair'],
        ['teal', ['bg' => '#ccfbf1', 'ring' => '#5eead4', 'skin' => '#f1c79f', 'shade' => '#dcaa7f', 'hair' => '#d69e4a', 'shirt' => '#0f766e', 'style' => 'long'], 'person with long blonde hair'],
        ['gold', ['bg' => '#fef3c7', 'ring' => '#fcd34d', 'skin' => '#c68642', 'shade' => '#a96d33', 'hair' => '#2b1a10', 'shirt' => '#334155', 'style' => 'bald', 'beard' => true, 'glasses' => true], 'person with a beard and glasses'],
        ['purple', ['bg' => '#ede9fe', 'ring' => '#c4b5fd', 'skin' => '#e0a878', 'shade' => '#c78c5e', 'hair' => '#7c2d12', 'shirt' => '#7c3aed', 'style' => 'bun'], 'person with auburn hair in a bun'],
        ['forest', ['bg' => '#dcfce7', 'ring' => '#86efac', 'skin' => '#5e3a24', 'shade' => '#4b2c19', 'hair' => '#0f766e', 'shirt' => '#facc15', 'style' => 'scarf'], 'person wearing a teal headscarf'],
        ['sunset', ['bg' => '#ffedd5', 'ring' => '#fdba74', 'skin' => '#f8d9c4', 'shade' => '#e8bca2', 'hair' => '#9ca3af', 'shirt' => '#c2410c', 'style' => 'bob', 'glasses' => true], 'person with a grey bob and glasses'],
        ['slate', ['bg' => '#e2e8f0', 'ring' => '#94a3b8', 'skin' => '#a86b45', 'shade' => '#8e5634', 'hair' => '#111827', 'shirt' => '#0ea5e9', 'style' => 'pony'], 'person with a dark ponytail'],
    ];
    foreach ($avatars as $i => [$p, $opts, $who]) {
        $bgName = ['blue' => 'light blue', 'rose' => 'pink', 'teal' => 'mint', 'gold' => 'pale yellow', 'purple' => 'lavender', 'forest' => 'light green', 'sunset' => 'peach', 'slate' => 'light grey'][$p];
        $add('avatar-' . ($i + 1), 'avatar', $p, 400, 400, 'light', 'Illustrated avatar of a smiling ' . $who . ' on a ' . $bgName . ' background', static fn (Rng $r) => avatar($opts));
    }

    $logos = [
        ['blue', 'light', 'Placeholder logo: blue rounded-square emblem with a sparkle and abstract wordmark bars (no text)', 'logo_1'],
        ['teal', 'light', 'Placeholder logo: teal hexagon emblem and abstract wordmark bars (no text)', 'logo_2'],
        ['purple', 'light', 'Placeholder logo: overlapping purple, pink and yellow circles with abstract wordmark bars (no text)', 'logo_3'],
        ['white', 'dark', 'Placeholder logo in white for dark backgrounds: triangle emblem and abstract wordmark bars (no text)', 'logo_4'],
    ];
    foreach ($logos as $i => [$p, $tone, $alt, $fn]) {
        $add('logo-' . ($i + 1), 'logo', $p, 600, 200, $tone, $alt, $fn);
    }

    return $list;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function ratio(int $w, int $h): string
{
    $a = $w;
    $b = $h;
    while ($b !== 0) {
        [$a, $b] = [$b, $a % $b];
    }

    return ($w / $a) . ':' . ($h / $a);
}

$root   = dirname(__DIR__);
$outDir = $argv[1] ?? $root . '/wp-plugin/assets/images';
if (!is_dir($outDir) && !mkdir($outDir, 0777, true) && !is_dir($outDir)) {
    fwrite(STDERR, "Cannot create {$outDir}\n");
    exit(1);
}

$images = [];
$errors = [];
foreach (catalogue() as $n => $item) {
    $seed       = 1000 + $n * 7919;
    [$defs, $b] = ($item['fn'])(new Rng($seed));
    $svg        = svg($item['w'], $item['h'], $item['alt'], $defs, $b);
    $file       = $item['token'] . '.svg';

    // Self-checks mirror tests/ImagePackTest.php so a bad build fails here first.
    if (strlen($svg) > 61440) {
        $errors[] = "{$file} is " . strlen($svg) . ' bytes (> 60 KB)';
    }
    if (preg_match('#(href|src)="https?://#i', $svg) || preg_match('/on[a-z]+\s*=/i', $svg) || stripos($svg, '<script') !== false) {
        $errors[] = "{$file} contains a forbidden construct";
    }
    if (function_exists('simplexml_load_string')) {
        libxml_use_internal_errors(true);
        if (simplexml_load_string($svg) === false) {
            $errors[] = "{$file} is not well-formed XML";
        }
        libxml_clear_errors();
    }

    file_put_contents($outDir . '/' . $file, $svg);
    $images[] = [
        'token'   => $item['token'],
        'file'    => $file,
        'ratio'   => ratio($item['w'], $item['h']),
        'width'   => $item['w'],
        'height'  => $item['h'],
        'palette' => $item['palette'],
        'role'    => $item['role'],
        'tone'    => $item['tone'],
        'alt'     => $item['alt'],
    ];
}

$manifest = ['fallback' => 'square-slate-1', 'images' => $images];
file_put_contents($outDir . '/manifest.json', json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . "\n");

$readme = <<<TXT
JHMG AI Editor for Divi 5 - built-in image pack
================================================

Original artwork generated by a script in the plugin's development repository, © JHMG, released under GPL-2.0-or-later.

Every image in this folder is an original SVG illustration produced by a
deterministic generator script. None of it is a photograph and none of it is
taken from a third-party stock library. The files are served from this plugin's
own folder on your site; nothing is loaded from a remote host.

manifest.json lists every image with its token, role (hero, section-bg, card,
square, avatar, logo), aspect ratio, palette, tone (dark = use light text on it,
light = use dark text on it) and alt text. Page layouts reference images with
tokens such as {{aied:image:hero-blue-1}}, which the plugin resolves to the URL
of the matching file in this folder.

TXT;
file_put_contents($outDir . '/README.txt', $readme);

if ($errors !== []) {
    fwrite(STDERR, implode("\n", $errors) . "\n");
    exit(1);
}

echo 'Wrote ' . count($images) . " images + manifest.json + README.txt to {$outDir}\n";
