<?php

declare(strict_types=1);

namespace Divi5Validator\Tools;

/** Turns verification evidence into the sets the schema consumes. Only `pass` is promoted. */
final class Promoter
{
    /**
     * @param list<array{name:string, children:list<string>, isChild:bool}> $proposals
     * @param array<string, array{status:string, placements_rendered:list<string>}> $results
     * @return array{leaf:list<string>, structural:list<string>, columnChildren:list<string>, sectionChildren:list<string>, children:array<string,list<string>>}
     */
    public static function promote(array $proposals, array $results): array
    {
        $sets = ['leaf' => [], 'structural' => [], 'columnChildren' => [], 'sectionChildren' => [], 'children' => []];

        foreach ($proposals as $p) {
            $r = $results[$p['name']] ?? null;
            if ($p['isChild'] || $r === null || $r['status'] !== 'pass') {
                continue;
            }

            if ($p['children'] === []) {
                $sets['leaf'][] = $p['name'];
            } else {
                $sets['structural'][] = $p['name'];
                $kids = $p['children'];
                sort($kids);
                $sets['children'][$p['name']] = $kids;
                foreach ($kids as $kid) {
                    $sets['leaf'][] = $kid;
                }
            }
            if (in_array('column', $r['placements_rendered'], true)) {
                $sets['columnChildren'][] = $p['name'];
            }
            // 'section' evidence is deliberately NOT promoted: a render that succeeds in a section
            // does not prove Divi's builder allows the module there (see Task 3 review).
        }

        foreach (['leaf', 'structural', 'columnChildren', 'sectionChildren'] as $k) {
            $sets[$k] = array_values(array_unique($sets[$k]));
            sort($sets[$k]);
        }
        ksort($sets['children']);

        return $sets;
    }

    /** @param array<string, mixed> $sets */
    public static function render(array $sets, string $version): string
    {
        $list = function (array $items): string {
            return $items === [] ? '[]' : "[\n" . implode('', array_map(fn ($i) => "        '" . $i . "',\n", $items)) . '    ]';
        };
        $map = function (array $items): string {
            if ($items === []) {
                return '[]';
            }
            $out = "[\n";
            foreach ($items as $k => $v) {
                $out .= "        '" . $k . "' => ['" . implode("', '", $v) . "'],\n";
            }

            return $out . '    ]';
        };

        return "<?php\n\ndeclare(strict_types=1);\n\nnamespace Divi5Validator;\n\n"
            . "/**\n * GENERATED by scripts/promote-modules.php from docs/module-verification-*.json.\n"
            . " * Do not edit by hand: every entry is backed by a render-verification record.\n */\n"
            . "final class VerifiedModules\n{\n"
            . "    public const DIVI_VERSION = '" . $version . "';\n\n"
            . '    public const LEAF = ' . $list($sets['leaf']) . ";\n\n"
            . '    public const STRUCTURAL = ' . $list($sets['structural']) . ";\n\n"
            . '    public const COLUMN_CHILDREN = ' . $list($sets['columnChildren']) . ";\n\n"
            . '    public const SECTION_CHILDREN = ' . $list($sets['sectionChildren']) . ";\n\n"
            . '    public const CHILDREN = ' . $map($sets['children']) . ";\n}\n";
    }
}
